using System.Text.Json;
using System.Text.Json.Serialization;
using Avalon.Configuration;
using Avalon.Database.World;
using Avalon.Domain.World;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace Avalon.Exporter;

/// <summary>
/// Exports the aura rows a client names and draws auras from (auras): SMSG_AURA_UPDATE and SMSG_AURA_LIST carry an aura
/// id and its timing, and a client needs the name, icon, kind and stat modifiers to show it. Like ability-catalog it
/// reads the World database and is reviewed as a data diff. A hand-listed row: the base, the scaling and the script are
/// server-only balance. Enumerations are written as their numbers, listed in the $comment.
/// </summary>
public static class AuraCatalogExport
{
    public const string DirectoryName = "auras";
    public const string FileName = "aura-catalog-v1.json";

    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>The same World connection string item-catalog reads, from the same sources.</summary>
    public static string? Readiness() => ItemCatalog.Readiness();

    public static void Write(string path)
    {
        string connectionString = ItemCatalog.ConnectionString()
            ?? throw new InvalidOperationException("No World connection string; readiness should have caught this.");

        IOptions<DatabaseConfiguration> options = Options.Create(new DatabaseConfiguration
        {
            World = new DatabaseConnection { ConnectionString = connectionString },
        });

        using var context = new WorldDbContext(NullLoggerFactory.Instance, options);
        List<AuraTemplate> auras = context.AuraTemplates.AsNoTracking().Include(a => a.Modifiers).ToList();

        Lf.Write(path, Render(auras));
        Console.WriteLine($"wrote {path} ({auras.Count} aura templates)");
    }

    /// <summary>Pure, so the shape of the file is testable without a database.</summary>
    public static string Render(IReadOnlyCollection<AuraTemplate> auras)
    {
        var document = new CatalogDocument(
            Comment: "Generated by tools/Avalon.Exporter -- aura-catalog. Do not edit by hand. kind: 1 helpful, 2 harmful. " +
                     "periodicKind: 0 none, 1 damage, 2 heal. stacking: 1 refresh, 2 stack (up to maxStacks), 3 one per " +
                     "caster. Modifiers: stat 1 armor, 2 attack damage, 3 ability damage, 4 crit %, 5 dodge %, 6 block %, " +
                     "7 haste %, 8 movement speed %, 9 max health, 10 max power; kind 1 flat, 2 percent; each times the " +
                     "stacks held. durationMs and tickIntervalMs in milliseconds; 0 ticks never.",
            Auras: auras.OrderBy(a => a.Id.Value).Select(Row.From).ToList());

        return JsonSerializer.Serialize(document, SerializerOptions) + "\n";
    }

    private sealed record CatalogDocument(
        [property: JsonPropertyName("$comment")] string Comment,
        List<Row> Auras);

    private sealed record Modifier(byte Stat, byte Kind, float Value);

    private sealed record Row(
        uint Id, string Name, string Icon, byte Kind, uint DurationMs, uint TickIntervalMs, byte PeriodicKind,
        byte Stacking, uint MaxStacks, List<Modifier> Modifiers)
    {
        public static Row From(AuraTemplate t) => new(
            t.Id.Value, t.Name ?? string.Empty, t.Icon ?? string.Empty, (byte)t.Kind, t.DurationMs, t.TickIntervalMs,
            (byte)t.PeriodicKind, (byte)t.Stacking, t.MaxStacks,
            t.Modifiers.OrderBy(m => m.Stat).Select(m => new Modifier((byte)m.Stat, (byte)m.Kind, m.Value)).ToList());
    }
}
