using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using Avalon.Common;
using Avalon.Common.Converters;
using Avalon.Configuration;
using Avalon.Database.World;
using Avalon.Domain.World;
using Avalon.World.Public.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace Avalon.Exporter;

/// <summary>
/// Exports the item template rows the client vendors -- the only artifact that turns the template
/// id an inventory packet carries into a name, an icon and stats. Unlike every other export here
/// this one reads a database, so its content changes when game data changes rather than when code
/// does -- no drift test can hold it to anything, and it is reviewed as a data diff.
///
/// DEVIATION FROM THE ORIGINAL PLAN: the plan's brief for this task defined a hand-written 13-field
/// CatalogRow projection. That is not used here. The companion item-schema-v1.json (Task 9) already
/// describes every field ItemTemplate has -- including the damage and stat columns a tooltip needs
/// -- and a second, narrower, hand-maintained list of fields is exactly the kind of thing that
/// silently drifts from it. Instead the rows are the entity itself, serialized directly: the schema
/// (reflection over ItemTemplate's properties) and the catalog (this file, reflection-driven System.
/// Text.Json over the same properties) agree by construction because there is only one list of
/// fields, not two. ItemTemplate has no navigation properties, so this is safe.
/// </summary>
public static class ItemCatalog
{
    public const string DirectoryName = "items";
    public const string FileName = "item-catalog-v1.json";

    // camelCase, matching opcodes.json and item-schema-v1.json.
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new ValueObjectJsonConverterFactory() },
        TypeInfoResolver = new DefaultJsonTypeInfoResolver()
            .WithAddedModifier(NeverOmitName)
            .WithAddedModifier(ForceNumericAllowedClasses),
    };

    public static string? Readiness() => ReadinessFor(ConnectionString());

    public static string? ReadinessFor(string? connectionString) =>
        string.IsNullOrWhiteSpace(connectionString)
            ? "needs a World database connection: set Database__World__ConnectionString, " +
              "or start one with `docker compose up -d postgres`."
            : null;

    public static void Write(string path)
    {
        string connectionString = ConnectionString()
            ?? throw new InvalidOperationException("No World connection string; readiness should have caught this.");

        IOptions<DatabaseConfiguration> options = Options.Create(new DatabaseConfiguration
        {
            World = new DatabaseConnection { ConnectionString = connectionString }
        });

        using var context = new WorldDbContext(NullLoggerFactory.Instance, options);

        List<ItemTemplate> templates = context.ItemTemplates.AsNoTracking().ToList();

        Lf.Write(path, Render(templates));
        Console.WriteLine($"wrote {path} ({templates.Count} item templates)");
    }

    /// <summary>Pure, so the shape of the file is testable without a database.</summary>
    public static string Render(IReadOnlyCollection<ItemTemplate> templates)
    {
        var document = new CatalogDocument(
            Comment: "Generated by tools/Avalon.Exporter -- item-catalog. Do not edit by hand. " +
                     "Field meanings and enum values are in item-schema-v1.json.",
            Items: templates.OrderBy(template => template.Id.Value).ToList());

        return JsonSerializer.Serialize(document, SerializerOptions) + "\n";
    }

    /// <summary>
    /// The column is nullable in practice, and a client parsing null into a label shows nothing
    /// where a name belongs (CharacterService.MapItem already coalesces the same way). This is the
    /// one field whose read is patched rather than left to the entity's own reflection: overriding
    /// the property getter for serialization means it never hands DefaultIgnoreCondition.
    /// WhenWritingNull a null to act on, so the field is never dropped -- and every other property
    /// still follows the entity by construction, with nothing hand-listed alongside it.
    /// </summary>
    private static void NeverOmitName(JsonTypeInfo typeInfo)
    {
        if (typeInfo.Type != typeof(ItemTemplate)) return;

        JsonPropertyInfo? name = typeInfo.Properties.FirstOrDefault(
            property => property.AttributeProvider is System.Reflection.MemberInfo member
                        && member.Name == nameof(ItemTemplate.Name));

        if (name is null) return;

        name.Get = static obj => ((ItemTemplate)obj).Name ?? string.Empty;
    }

    /// <summary>
    /// ItemTemplate.AllowedClasses is List&lt;CharacterClass&gt;, and CharacterClass carries
    /// [JsonConverter(typeof(JsonStringEnumConverter))] -- deliberately, for Avalon.Api's REST
    /// responses, and out of scope to change here. A type-level [JsonConverter] attribute beats
    /// anything in JsonSerializerOptions.Converters, so without this modifier the reflection-driven
    /// serialization below would emit ["Warrior", "Wizard", ...] while item-schema-v1.json and every
    /// sibling enum field (class, subClass, rarity, flags, damageType1, statType1) emit the numeric
    /// vocabulary the schema promises. Setting CustomConverter on the property itself outranks a
    /// type-level attribute -- the same precedence a property-level [JsonConverter] would have --
    /// which is why this works where adding to Converters would not.
    ///
    /// This artifact has no drift guard by design (see the class remarks): if some other domain enum
    /// later grows its own [JsonConverter], nothing here will fail -- the catalog will just silently
    /// start emitting that field as strings. Check every enum field against item-schema-v1.json's
    /// numeric vocabularies before trusting a regenerated catalog.
    /// </summary>
    private static void ForceNumericAllowedClasses(JsonTypeInfo typeInfo)
    {
        if (typeInfo.Type != typeof(ItemTemplate)) return;

        JsonPropertyInfo? allowedClasses = typeInfo.Properties.FirstOrDefault(
            property => property.AttributeProvider is System.Reflection.MemberInfo member
                        && member.Name == nameof(ItemTemplate.AllowedClasses));

        if (allowedClasses is null) return;

        allowedClasses.CustomConverter = new NumericEnumListConverter<CharacterClass>();
    }

    private static string? ConnectionString()
    {
        IConfigurationRoot configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.Design.json", optional: true)
            .AddJsonFile("appsettings.json", optional: true)
            .AddEnvironmentVariables()
            .Build();

        var database = new DatabaseConfiguration();
        configuration.GetSection("Database").Bind(database);

        return database.World?.ConnectionString ?? configuration["Database:World:ConnectionString"];
    }

    private sealed record CatalogDocument(
        [property: JsonPropertyName("$comment")] string Comment,
        List<ItemTemplate> Items);

    /// <summary>
    /// Writes each element's underlying numeric value directly, bypassing whatever
    /// [JsonConverter] the enum type itself carries. See <see cref="ForceNumericAllowedClasses"/>
    /// for why this export needs to override that rather than follow it.
    /// </summary>
    private sealed class NumericEnumListConverter<TEnum> : JsonConverter<List<TEnum>>
        where TEnum : struct, Enum
    {
        public override List<TEnum> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            => throw new NotSupportedException($"{nameof(ItemCatalog)} only writes this artifact, never reads it.");

        public override void Write(Utf8JsonWriter writer, List<TEnum> value, JsonSerializerOptions options)
        {
            writer.WriteStartArray();
            foreach (TEnum item in value)
                writer.WriteNumberValue(Convert.ToInt64(item));
            writer.WriteEndArray();
        }
    }
}
