name: '$(Date:yyyyMMdd).$(rev:r)'

trigger:
  branches:
    include:
      - main

pool:
  name: CI

variables:
  - name: dockerRegistryServiceConnection
    value: 'Private Registry'

  - name: dockerHubContainerRegistry
    value: $(registryUrl)
  - name: dockerHubUsername
    value: $(registryUsername)
  - name: dockerHubPassword
    value: $(registryPassword)

  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: 'Avalon.sln'

  - name: MajorVersion
    value: 0
  - name: MinorVersion
    value: 0
  - name: PatchVersion
    value: 19

resources:
  repositories:
    - repository: BuildSteps
      type: git
      name: Avalon/BuildSteps
      ref: refs/heads/main

jobs:

  - job: 'ci_build_test'
    displayName: 'CI Build + Test'
    timeoutInMinutes: 15 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
    steps:
      - checkout: self
        persistCredentials: true
        submodules: true

      - script: dotnet new --install MonoGame.Templates.CSharp
        displayName: 'Install .NET MonoGame Templates'

      - template: 'dotnet/restore-solution.yml@BuildSteps'
      - template: 'dotnet/build-solution.yml@BuildSteps'
      - template: 'dotnet/test-solution.yml@BuildSteps'

      # Pack Network Packets
      #- template: 'dotnet/update-assembly.yml@BuildSteps'
      #  parameters:
      #    project: 'src/Shared/Avalon.Network.Packets/*.csproj'
      #    product: 'Avalon.Network.Packets'
      #    description: 'Network packets reference used by Avalon Game Server'
      - template: 'dotnet/nuget-pack.yml@BuildSteps'
        parameters:
          project: 'src/Shared/Avalon.Network.Packets/*.csproj'
      # Pack Network Packets end
      # Pack Network Packets
      #- template: 'dotnet/update-assembly.yml@BuildSteps'
      #  parameters:
      #    project: 'src/Shared/Avalon.Network.Packets/*.csproj'
      #    product: 'Avalon.Network.Packets'
      #    description: 'Network packets reference used by Avalon Game Server'
      - template: 'dotnet/nuget-pack.yml@BuildSteps'
        parameters:
          project: 'src/Shared/Avalon.Network.Packets/*.csproj'
      # Pack Network Packets end
      # Pack Network Tcp
      #- template: 'dotnet/update-assembly.yml@BuildSteps'
      #  parameters:
      #    project: 'src/Shared/Avalon.Network.Tcp/*.csproj'
      #    product: 'Avalon.Network.Tcp'
      #    description: 'TCP client and server used by Avalon'
      - template: 'dotnet/nuget-pack.yml@BuildSteps'
        parameters:
          project: 'src/Shared/Avalon.Network.Tcp/*.csproj'
      # Pack Network Tcp end
      # Pack Domain
      #- template: 'dotnet/update-assembly.yml@BuildSteps'
      #  parameters:
      #    project: 'src/Shared/Avalon.Domain/*.csproj'
      #    product: 'Avalon.Domain'
      #    description: 'Domain layer used by Avalon'
      - template: 'dotnet/nuget-pack.yml@BuildSteps'
        parameters:
          project: 'src/Shared/Avalon.Domain/*.csproj'
      # Pack Domain end
      - template: 'dotnet/nuget-publish.yml@BuildSteps'

      # Api Start
      - task: DotNetCoreCLI@2
        displayName: '.NET Publish Api'
        inputs:
          command: 'publish'
          arguments: 'src/Server/Avalon.Api/Avalon.Api.csproj -c Release --no-restore'
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false

      - template: 'docker/build.yml@BuildSteps'
        parameters:
          imageRepository: '$(registryUrl)/avalon/avalon-api'
          dockerfilePath: 'src/Server/Avalon.Api/Dockerfile'

      - task: Bash@3
        displayName: Docker Push - avalon-api - $(Build.BuildNumber)
        inputs:
          targetType: 'inline'
          script: |
            #!/bin/bash
            docker push $(registryUrl)/avalon/avalon-api:$(Build.BuildNumber)
            docker push $(registryUrl)/avalon/avalon-api:latest

      - template: 'helm/package.yml@BuildSteps'
        parameters:
          helmName: 'avalon-api'
          helmChartPath: '$(Build.SourcesDirectory)/src/Server/Avalon.Api/Helm'

      - task: Bash@3
        displayName: 'Helm OCI Publish - avalon-api - $(Build.BuildNumber)'
        inputs:
          targetType: 'bash'
          scriptLocation: 'inlineScript'
          script: |
            ls
            helm push avalon-api-$(Build.BuildNumber)-helm.tgz oci://$(registryUrl)/avalon
            helm push avalon-api-0.0-latest.tgz oci://$(registryUrl)/avalon
      # Api End

      # Game Server Start
      - task: DotNetCoreCLI@2
        displayName: '.NET Publish Server'
        inputs:
          command: 'publish'
          arguments: 'src/Server/Avalon.Server.World/Avalon.Server.World.csproj -c Release --no-restore'
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false

      - task: Bash@3
        displayName: 'Docker Build - world-server - $(Build.BuildNumber)'
        inputs:
          targetType: 'inline'
          script: |
            #!/bin/bash
            docker build --no-cache -t $(registryUrl)/avalon/world-server:$(Build.BuildNumber) -f src/Server/Avalon.Server.World/Dockerfile src/Server/Avalon.Server.World
            docker tag $(registryUrl)/avalon/world-server:$(Build.BuildNumber) $(registryUrl)/avalon/world-server:latest

      - task: Bash@3
        displayName: 'Docker Push - world-server - $(Build.BuildNumber)'
        inputs:
          targetType: 'inline'
          script: |
            #!/bin/bash
            docker push $(registryUrl)/avalon/world-server:$(Build.BuildNumber)
            docker push $(registryUrl)/avalon/world-server:latest

      - template: 'helm/package.yml@BuildSteps'
        parameters:
          helmName: 'world-server'
          helmChartPath: '$(Build.SourcesDirectory)/src/Server/Avalon.Server.World/Helm'

      - task: Bash@3
        displayName: 'Helm OCI Publish - world-server - $(Build.BuildNumber)'
        inputs:
          targetType: 'bash'
          scriptLocation: 'inlineScript'
          script: |
            ls
            helm push world-server-$(Build.BuildNumber)-helm.tgz oci://$(registryUrl)/avalon
            helm push world-server-0.0-latest.tgz oci://$(registryUrl)/avalon
      # Game Server End

      # Auth Server Start
      - task: DotNetCoreCLI@2
        displayName: '.NET Publish Server'
        inputs:
          command: 'publish'
          arguments: 'src/Server/Avalon.Server.Auth/Avalon.Server.Auth.csproj -c Release --no-restore'
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false

      - task: Bash@3
        displayName: 'Docker Build - auth-server - $(Build.BuildNumber)'
        inputs:
          targetType: 'inline'
          script: |
            #!/bin/bash
            docker build --no-cache -t $(registryUrl)/avalon/auth-server:$(Build.BuildNumber) -f src/Server/Avalon.Server.Auth/Dockerfile src/Server/Avalon.Server.Auth
            docker tag $(registryUrl)/avalon/auth-server:$(Build.BuildNumber) $(registryUrl)/avalon/auth-server:latest

      - task: Bash@3
        displayName: 'Docker Push - auth-server - $(Build.BuildNumber)'
        inputs:
          targetType: 'inline'
          script: |
            #!/bin/bash
            docker push $(registryUrl)/avalon/auth-server:$(Build.BuildNumber)
            docker push $(registryUrl)/avalon/auth-server:latest

      - template: 'helm/package.yml@BuildSteps'
        parameters:
          helmName: 'auth-server'
          helmChartPath: '$(Build.SourcesDirectory)/src/Server/Avalon.Server.Auth/Helm'

      - task: Bash@3
        displayName: 'Helm OCI Publish - auth-server - $(Build.BuildNumber)'
        inputs:
          targetType: 'bash'
          scriptLocation: 'inlineScript'
          script: |
            ls
            helm push auth-server-$(Build.BuildNumber)-helm.tgz oci://$(registryUrl)/avalon
            helm push auth-server-0.0-latest.tgz oci://$(registryUrl)/avalon
    # Auth Server End
