name: '$(Date:yyyyMMdd).$(rev:r)'

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'
 
pool:
  name: CI

variables:
- name: dockerRegistryServiceConnection
  value: 'Private Registry'

- name: dockerHubContainerRegistry
  value: $(registryUrl)
- name: dockerHubUsername
  value: $(registryUsername)
- name: dockerHubPassword
  value: $(registryPassword)

- name: buildConfiguration
  value: 'Release'
- name: solution
  value: 'Avalon.sln'

- name: MajorVersion
  value: 0
- name: MinorVersion
  value: 0
- name: PatchVersion
  value: 18

resources:
  repositories:
    - repository: BuildSteps
      type: git
      name: Avalon/BuildSteps
      ref: refs/heads/main

jobs:
- job: 'ci_build'
  displayName: 'CI Build'
  timeoutInMinutes: 15 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: dotnet new --install MonoGame.Templates.CSharp
    displayName: 'Install .NET MonoGame Templates'

  - template: 'dotnet/restore-solution.yml@BuildSteps'
  - template: 'dotnet/build-solution.yml@BuildSteps'
  - template: 'dotnet/test-solution.yml@BuildSteps'
  # Pack Network Packets
  - template: 'dotnet/update-assembly.yml@BuildSteps'
    parameters:
      project: 'src/Shared/Avalon.Network.Packets/*.csproj'
      product: 'Avalon.Network.Packets'
      description: 'Network packets reference used by Avalon Game Server'
  - template: 'dotnet/nuget-pack.yml@BuildSteps'
  #  parameters:
  #    project: 'src/Shared/Avalon.Network.Packets/*.csproj'
  # Pack Network Packets end
  # Pack Network Tcp
  #- template: 'dotnet/update-assembly.yml@BuildSteps'
  #  parameters:
  #    project: 'src/Shared/Avalon.Network.Tcp/*.csproj'
  #    product: 'Avalon.Network.Tcp'
  #    description: 'TCP client and server used by Avalon'
  #- template: 'dotnet/nuget-pack.yml@BuildSteps'
  #  parameters:
  #    project: 'src/Shared/Avalon.Network.Tcp/*.csproj'
  # Pack Network Tcp end
  # Pack Network Udp
  #- template: 'dotnet/update-assembly.yml@BuildSteps'
  #  parameters:
  #    project: 'src/Shared/Avalon.Network.Udp/*.csproj'
  #    product: 'Avalon.Network.Udp'
  #    description: 'UDP client and server used by Avalon'
  #- template: 'dotnet/nuget-pack.yml@BuildSteps'
  #  parameters:
  #    project: 'src/Shared/Avalon.Network.Udp/*.csproj'
  # Pack Network Udp end
  - template: 'dotnet/nuget-publish.yml@BuildSteps'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: 'src/Server/Avalon.Server/Avalon.Server.csproj -c Release --no-restore'
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
    displayName: '.NET Publish Server'
  
  - template: 'docker/build.yml@BuildSteps'
    parameters:
      imageRepository: '$(registryUrl)/avalon/game-server'
      dockerfilePath: 'src/Server/Avalon.Server/Dockerfile'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        #!/bin/bash
        docker push $(registryUrl)/avalon/game-server:$(Build.BuildNumber)
        docker push $(registryUrl)/avalon/game-server:latest
        
  - template: 'helm/package.yml@BuildSteps'
    parameters:
      helmName: 'game-server'
      helmChartPath: '$(Build.SourcesDirectory)/src/Server/Avalon.Server/Helm'

  - task: Bash@3
    displayName:  Helm OCI Publish - game-server - $(Build.BuildNumber)
    inputs:
      targetType: 'bash'
      scriptLocation: 'inlineScript'
      script: |
        ls
        helm push game-server-$(Build.BuildNumber)-helm.tgz oci://$(registryUrl)/avalon
        helm push game-server-0.0-latest.tgz oci://$(registryUrl)/avalon
  #- task: Docker@2
  #  inputs:
  #    containerRegistry: 'Private Registry'
  #    repository: 'avalon/avalon-server'
  #    command: 'buildAndPush'
  #    Dockerfile: '
  #    buildContext: 'src/Server/Avalon.Server/'
  #  displayName: 'Docker Build&Publish'
