name: avalon
services:
  redis:
    image: redis:latest
    container_name: redis-server
    environment:
      - REDIS_PASSWORD=123
    command: [ "redis-server", "--requirepass", "123" ]
    ports:
      - "6379:6379"
    restart: unless-stopped

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - "3306:3306"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres-server
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    restart: unless-stopped
