// <auto-generated />
using System;
using Avalon.Auth.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalon.Auth.Database.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20240703234858_InitialV2")]
    partial class InitialV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.Auth.Account", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<short>("AccessLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastAttemptIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MuteBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MuteReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MuteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("SessionKey")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = (short)3,
                            Email = "admin@avalon.monster",
                            FailedLogins = 0,
                            JoinDate = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(5864),
                            LastAttemptIp = "",
                            LastIp = "127.0.0.1",
                            LastLogin = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(5868),
                            Locale = "en",
                            Locked = false,
                            MuteBy = "",
                            MuteReason = "",
                            OS = "WIN",
                            Online = false,
                            Salt = new byte[] { 36, 50, 97, 36, 49, 49, 36, 113, 75, 77, 69, 57, 74, 120, 90, 105, 56, 85, 47, 68, 122, 70, 79, 80, 102, 65, 76, 116, 46 },
                            SessionKey = new byte[0],
                            TotalTime = 0L,
                            Username = "ADMIN",
                            Verifier = new byte[] { 36, 50, 97, 36, 49, 49, 36, 113, 75, 77, 69, 57, 74, 120, 90, 105, 56, 85, 47, 68, 122, 70, 79, 80, 102, 65, 76, 116, 46, 107, 50, 122, 99, 55, 48, 122, 85, 82, 75, 121, 112, 83, 48, 66, 121, 80, 88, 89, 57, 103, 70, 109, 49, 84, 69, 102, 84, 120, 78, 113 }
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AvalonToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.Device", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUsage")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TrustEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Trusted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.MFASetup", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("RecoveryCode1")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RecoveryCode2")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RecoveryCode3")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Secret")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<ushort>("Status")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("MfaSetups");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<uint>("Index")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Usages")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.World", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<short>("AccessLevelRequired")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MinVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Worlds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevelRequired = (short)2,
                            CreatedAt = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(6386),
                            Host = "127.0.0.1",
                            MinVersion = "0.0.1",
                            Name = "Development",
                            Port = 21001,
                            Status = (short)1,
                            Type = (short)0,
                            UpdatedAt = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(6386),
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = 2,
                            AccessLevelRequired = (short)0,
                            CreatedAt = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(6388),
                            Host = "asthoria.avalon.monster",
                            MinVersion = "0.0.1",
                            Name = "Asthoria",
                            Port = 21001,
                            Status = (short)0,
                            Type = (short)0,
                            UpdatedAt = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(6389),
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = 3,
                            AccessLevelRequired = (short)8,
                            CreatedAt = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(6391),
                            Host = "ptr.avalon.monster",
                            MinVersion = "0.0.1",
                            Name = "Public Test Realm",
                            Port = 21001,
                            Status = (short)0,
                            Type = (short)0,
                            UpdatedAt = new DateTime(2024, 7, 3, 23, 48, 58, 53, DateTimeKind.Utc).AddTicks(6391),
                            Version = "0.0.1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
