// <auto-generated />
using System;
using Avalon.Auth.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalon.Auth.Database.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20240703215024_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.Auth.Account", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<short>("AccessLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastAttemptIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MuteBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MuteReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MuteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("SessionKey")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = (short)3,
                            Email = "admin@avalon.monster",
                            FailedLogins = 0,
                            JoinDate = new DateTime(2024, 7, 3, 21, 50, 23, 607, DateTimeKind.Utc).AddTicks(5516),
                            LastAttemptIp = "",
                            LastIp = "127.0.0.1",
                            LastLogin = new DateTime(2024, 7, 3, 21, 50, 23, 607, DateTimeKind.Utc).AddTicks(5520),
                            Locale = "en",
                            Locked = false,
                            MuteBy = "",
                            MuteReason = "",
                            OS = "WIN",
                            Online = false,
                            Salt = new byte[] { 36, 50, 97, 36, 49, 49, 36, 106, 76, 81, 118, 71, 81, 53, 118, 75, 117, 105, 109, 107, 67, 110, 116, 84, 108, 107, 48, 108, 46 },
                            SessionKey = new byte[0],
                            TotalTime = 0L,
                            Username = "admin",
                            Verifier = new byte[] { 36, 50, 97, 36, 49, 49, 36, 106, 76, 81, 118, 71, 81, 53, 118, 75, 117, 105, 109, 107, 67, 110, 116, 84, 108, 107, 48, 108, 46, 89, 106, 119, 121, 66, 47, 101, 115, 79, 113, 114, 57, 49, 74, 108, 114, 113, 118, 75, 118, 117, 110, 80, 65, 70, 71, 68, 97, 112, 51, 79 }
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AvalonToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.Device", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUsage")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TrustEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Trusted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.MFASetup", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("RecoveryCode1")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RecoveryCode2")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RecoveryCode3")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Secret")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<ushort>("Status")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("MfaSetups");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<uint>("Index")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Usages")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.World", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<short>("AccessLevelRequired")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MinVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });
#pragma warning restore 612, 618
        }
    }
}
