using Avalon.Database.World.Seeding;

namespace Avalon.ChunkGen;

/// <summary>
/// The tool's command (Program.cs runs it with <see cref="ForestPieces" />). Every piece is first written into a
/// temporary copy of Maps/, read back through the World server's own catalog reader
/// (ChunkCatalogSeeder.ReadCatalogAsync) and baked with its own ChunkLayoutNavmeshBuilder, each set piece with its members
/// at their cells; only when all of that passes are the files copied into Maps/Chunks. Any failure before that exits 1
/// and writes nothing to Maps/.
/// </summary>
public static class ChunkGenCli
{
    public const string Usage = "usage: Avalon.ChunkGen forest [--maps <Maps directory>]";

    public static async Task<int> RunAsync(
        string[] args, Func<IReadOnlyList<ChunkPiece>> singles, Func<IReadOnlyList<ChunkGroupPiece>> groups,
        TextWriter output, TextWriter error)
    {
        if (!TryParse(args, out string? mapsArgument))
        {
            await error.WriteLineAsync(Usage);
            return 1;
        }

        string staging = Path.Combine(Path.GetTempPath(), $"avalon-chunkgen-{Guid.NewGuid():N}");
        string maps;
        IReadOnlyList<(string Name, string Obj, string Json)> files;
        try
        {
            maps = mapsArgument is null
                ? Path.Combine(RepositoryRoot.Find(), "src", "Server", "Avalon.Server.World", "Maps")
                : Path.GetFullPath(mapsArgument);
            IReadOnlyList<ChunkPiece> singlePieces = singles();
            IReadOnlyList<ChunkGroupPiece> groupPieces = groups();
            List<List<(ChunkPiece Piece, int CellX, int CellZ)>> groupMembers = groupPieces.Select(g => g.Members().ToList()).ToList();
            files = ChunkFiles.For(singlePieces, groupPieces);

            string stagedMaps = Path.Combine(staging, "Maps");
            foreach (string file in Directory.EnumerateFiles(maps, "*", SearchOption.AllDirectories))
            {
                string target = Path.Combine(stagedMaps, Path.GetRelativePath(maps, file));
                Directory.CreateDirectory(Path.GetDirectoryName(target)!);
                File.Copy(file, target);
            }
            foreach ((string name, string obj, string json) in files)
            {
                await File.WriteAllTextAsync(Path.Combine(stagedMaps, "Chunks", name + ".obj"), obj);
                await File.WriteAllTextAsync(Path.Combine(stagedMaps, "Chunks", name + ".json"), json);
            }

            await ChunkCatalogSeeder.ReadCatalogAsync(stagedMaps);
            foreach (ChunkPiece piece in singlePieces)
                PieceBake.Check(staging, [(piece.Name, 0, 0)]);
            foreach (List<(ChunkPiece Piece, int CellX, int CellZ)> members in groupMembers)
                PieceBake.Check(staging, members.Select(m => (m.Piece.Name, m.CellX, m.CellZ)).ToList());
        }
        catch (Exception ex)
        {
            await error.WriteLineAsync($"nothing written: {ex.GetType().Name}: {ex.Message}");
            return 1;
        }
        finally
        {
            DeleteStaging(staging, error);
        }

        string chunks = Path.Combine(maps, "Chunks");
        try
        {
            foreach ((string name, string obj, string json) in files)
            {
                await File.WriteAllTextAsync(Path.Combine(chunks, name + ".obj"), obj);
                await File.WriteAllTextAsync(Path.Combine(chunks, name + ".json"), json);
            }
        }
        catch (Exception ex)
        {
            await error.WriteLineAsync($"writing {chunks} failed part way, rerun after fixing: {ex.GetType().Name}: {ex.Message}");
            return 1;
        }

        await output.WriteLineAsync($"validated, baked and wrote {files.Count} chunks to {chunks}");

        // Listed, never deleted: a forest file the tool did not write is either hand-authored or left over from a renamed piece.
        var written = files.Select(f => f.Name).ToHashSet(StringComparer.Ordinal);
        foreach (string file in Directory.EnumerateFiles(chunks, "forest_*")
                     .Select(Path.GetFileName).OfType<string>()
                     .Where(f => f.EndsWith(".obj", StringComparison.Ordinal) || f.EndsWith(".json", StringComparison.Ordinal))
                     .Where(f => !written.Contains(Path.GetFileNameWithoutExtension(f)))
                     .Order(StringComparer.Ordinal))
            await output.WriteLineAsync($"not generated by ChunkGen: {file}");

        return 0;
    }

    /// <summary>
    /// Removes the temporary copy of Maps/. A copy that cannot be removed (a file held open in it, say) is only reported:
    /// it runs in a finally, where a throw would replace the run's own exit code and message.
    /// </summary>
    public static void DeleteStaging(string staging, TextWriter error, Action<string>? delete = null)
    {
        try
        {
            if (Directory.Exists(staging)) (delete ?? (path => Directory.Delete(path, recursive: true)))(staging);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            error.WriteLine($"could not remove the temporary copy {staging}: {ex.GetType().Name}: {ex.Message}");
        }
    }

    /// <summary>Exactly "forest", optionally followed by "--maps &lt;dir&gt;"; anything else is refused.</summary>
    private static bool TryParse(string[] args, out string? maps)
    {
        maps = null;
        if (args is ["forest"])
            return true;
        if (args is ["forest", "--maps", { Length: > 0 } dir] && !dir.StartsWith("--", StringComparison.Ordinal))
        {
            maps = dir;
            return true;
        }

        return false;
    }
}
