using System.Globalization;
using System.Text;

namespace Avalon.ChunkGen;

/// <summary>
/// Writes a piece or a town square as chunk-local OBJ (x/z 0-30, y up), the format ChunkLayoutNavmeshBuilder and the
/// client bake read: "o", "v x y z" and "f a b c" lines, plus, on a town square, one "usemtl" line after each tagged
/// object for the client's colours (the server ignores them, ChunkObjParserShould). LF line ends. Every face is wound
/// so (b-a)x(c-a) points out of its solid (a ring's out of its own segment), which is how Recast tells a walkable top
/// from a wall.
/// </summary>
public static class ObjWriter
{
    public static string Write(ChunkPiece piece)
    {
        var obj = new ObjBuilder();
        obj.Box("Floor", null, 0f, ChunkPiece.CellSize, -ChunkPiece.FloorThickness, 0f, 0f, ChunkPiece.CellSize);

        int n = 1;
        foreach (Blocker blocker in piece.Blockers)
        {
            string name = $"Blocker_{n++}";
            switch (blocker)
            {
                case BoxBlocker box:
                    obj.Box(name, null, box.MinX, box.MaxX, 0f, ChunkPiece.BlockerHeight, box.MinZ, box.MaxZ);
                    break;
                case CylinderBlocker cylinder:
                    obj.Cylinder(name, null, cylinder.X, cylinder.Z, cylinder.Radius, 0f, ChunkPiece.BlockerHeight);
                    break;
            }
        }

        return $"# Avalon chunk: {piece.Name}\n# Generated by tools/Avalon.ChunkGen; regenerate it rather than editing it by hand\n{obj}";
    }

    /// <summary>
    /// Today's floor and walls first (the floor untagged, the walls stone), then every piece as its own object, named
    /// building_part with _1, _2, ... on a name the square repeats (the posts).
    /// </summary>
    public static string Write(TownSquare square)
    {
        var obj = new ObjBuilder();
        obj.Box("Floor", null, 0f, TownSquare.CellSize, TownSquare.FloorBottom, TownSquare.FloorTop, 0f, TownSquare.CellSize);
        foreach (WallSegment wall in square.Walls)
            obj.Box(wall.Name, Materials.Name(Material.Stone), wall.MinX, wall.MaxX, 0f, WallSegment.Height, wall.MinZ, wall.MaxZ);

        var counts = square.Pieces.GroupBy(p => p.ObjectName, StringComparer.Ordinal).ToDictionary(g => g.Key, _ => 0, StringComparer.Ordinal);
        var repeated = square.Pieces.GroupBy(p => p.ObjectName, StringComparer.Ordinal).Where(g => g.Count() > 1).Select(g => g.Key)
            .ToHashSet(StringComparer.Ordinal);
        foreach (TownPiece piece in square.Pieces)
        {
            string name = piece.ObjectName;
            if (repeated.Contains(name)) name = $"{name}_{++counts[piece.ObjectName]}";
            string material = Materials.Name(piece.Material);
            switch (piece)
            {
                case BoxPiece box:
                    obj.Box(name, material, box.MinX, box.MaxX, box.Y0, box.Top, box.MinZ, box.MaxZ);
                    break;
                case CylinderPiece cylinder:
                    obj.Cylinder(name, material, cylinder.X, cylinder.Z, cylinder.Radius, cylinder.Y0, cylinder.Top);
                    break;
                case GablePiece gable:
                    obj.Gable(name, material, gable.MinX, gable.MaxX, gable.MinZ, gable.MaxZ, gable.Eaves, gable.Ridge, gable.RidgeAlongX);
                    break;
                case RingPiece ring:
                    obj.Ring(name, material, ring.X, ring.Z, ring.Radius, ring.InnerRadius, ring.Y0, ring.Top);
                    break;
            }
        }

        return $"# Avalon chunk: {square.Name}\n# Generated by tools/Avalon.ChunkGen (town); regenerate it rather than editing it by hand\n{obj}";
    }

    private sealed class ObjBuilder
    {
        private readonly StringBuilder _text = new();
        private readonly List<(float X, float Y, float Z)> _points = [];

        public void Box(string name, string? material, float x0, float x1, float y0, float y1, float z0, float z1)
        {
            Object(name, material);
            int b = _points.Count;
            Vertex(x0, y0, z0); Vertex(x1, y0, z0); Vertex(x1, y0, z1); Vertex(x0, y0, z1);
            Vertex(x0, y1, z0); Vertex(x1, y1, z0); Vertex(x1, y1, z1); Vertex(x0, y1, z1);
            (float, float, float) inside = ((x0 + x1) / 2f, (y0 + y1) / 2f, (z0 + z1) / 2f);
            Quad(inside, b + 4, b + 5, b + 6, b + 7);   // top
            Quad(inside, b + 0, b + 1, b + 2, b + 3);   // bottom
            Quad(inside, b + 0, b + 1, b + 5, b + 4);   // z0 side
            Quad(inside, b + 3, b + 2, b + 6, b + 7);   // z1 side
            Quad(inside, b + 0, b + 3, b + 7, b + 4);   // x0 side
            Quad(inside, b + 1, b + 2, b + 6, b + 5);   // x1 side
        }

        public void Cylinder(string name, string? material, float x, float z, float radius, float y0, float y1)
        {
            Object(name, material);
            int b = _points.Count;
            const int N = CylinderBlocker.Segments;
            for (int i = 0; i < N; i++)
            {
                double angle = 2.0 * Math.PI * i / N;
                Vertex(x + (float)(radius * Math.Cos(angle)), y0, z + (float)(radius * Math.Sin(angle)));
            }
            for (int i = 0; i < N; i++)
            {
                double angle = 2.0 * Math.PI * i / N;
                Vertex(x + (float)(radius * Math.Cos(angle)), y1, z + (float)(radius * Math.Sin(angle)));
            }
            int bottomCentre = _points.Count;
            Vertex(x, y0, z);
            int topCentre = _points.Count;
            Vertex(x, y1, z);

            (float x, float, float z) inside = (x, (y0 + y1) / 2f, z);
            for (int i = 0; i < N; i++)
            {
                int j = (i + 1) % N;
                Triangle(inside, topCentre, b + N + i, b + N + j);
                Triangle(inside, bottomCentre, b + i, b + j);
                Quad(inside, b + i, b + j, b + N + j, b + N + i);
            }
        }

        /// <summary>
        /// A twelve-sided ring: outer and inner walls, an annular top and bottom. A ring is not star-shaped about its
        /// centre, so each segment's faces are wound against that segment's own middle (mid-radius, mid-height).
        /// </summary>
        public void Ring(string name, string? material, float x, float z, float outer, float inner, float y0, float y1)
        {
            Object(name, material);
            int b = _points.Count;
            const int N = CylinderBlocker.Segments;
            foreach ((float radius, float y) in new[] { (outer, y0), (outer, y1), (inner, y0), (inner, y1) })
            {
                for (int i = 0; i < N; i++)
                {
                    double angle = 2.0 * Math.PI * i / N;
                    Vertex(x + (float)(radius * Math.Cos(angle)), y, z + (float)(radius * Math.Sin(angle)));
                }
            }

            // b + i outer bottom, b + n + i outer top, b + 2n + i inner bottom, b + 3n + i inner top.
            float mid = (outer + inner) / 2f;
            for (int i = 0; i < N; i++)
            {
                int j = (i + 1) % N;
                double angle = 2.0 * Math.PI * (i + 0.5) / N;
                (float, float, float) inside = (x + (float)(mid * Math.Cos(angle)), (y0 + y1) / 2f, z + (float)(mid * Math.Sin(angle)));
                Quad(inside, b + i, b + j, b + N + j, b + N + i);                           // outer wall
                Quad(inside, b + 2 * N + i, b + 2 * N + j, b + 3 * N + j, b + 3 * N + i);   // inner wall
                Quad(inside, b + N + i, b + N + j, b + 3 * N + j, b + 3 * N + i);           // top
                Quad(inside, b + i, b + j, b + 2 * N + j, b + 2 * N + i);                   // bottom
            }
        }

        /// <summary>A gabled prism: four eaves corners at y0, two ridge points at y1 along the middle of the ridge axis.</summary>
        public void Gable(string name, string? material, float x0, float x1, float z0, float z1, float y0, float y1, bool ridgeAlongX)
        {
            Object(name, material);
            int b = _points.Count;
            Vertex(x0, y0, z0); Vertex(x1, y0, z0); Vertex(x1, y0, z1); Vertex(x0, y0, z1);   // b+0..b+3, the eaves
            if (ridgeAlongX)
            {
                float zm = (z0 + z1) / 2f;
                Vertex(x0, y1, zm); Vertex(x1, y1, zm);                                      // b+4 west end, b+5 east end
                (float, float, float zm) inside = ((x0 + x1) / 2f, y0 + (y1 - y0) / 3f, zm);
                Quad(inside, b + 0, b + 1, b + 2, b + 3);           // bottom
                Quad(inside, b + 0, b + 1, b + 5, b + 4);           // south slope
                Quad(inside, b + 3, b + 2, b + 5, b + 4);           // north slope
                Triangle(inside, b + 0, b + 3, b + 4);              // west gable
                Triangle(inside, b + 1, b + 2, b + 5);              // east gable
            }
            else
            {
                float xm = (x0 + x1) / 2f;
                Vertex(xm, y1, z0); Vertex(xm, y1, z1);                                      // b+4 south end, b+5 north end
                (float xm, float, float) inside = (xm, y0 + (y1 - y0) / 3f, (z0 + z1) / 2f);
                Quad(inside, b + 0, b + 1, b + 2, b + 3);           // bottom
                Quad(inside, b + 0, b + 3, b + 5, b + 4);           // west slope
                Quad(inside, b + 1, b + 2, b + 5, b + 4);           // east slope
                Triangle(inside, b + 0, b + 1, b + 4);              // south gable
                Triangle(inside, b + 3, b + 2, b + 5);              // north gable
            }
        }

        public override string ToString() => _text.ToString();

        private void Object(string name, string? material)
        {
            _text.Append("o ").Append(name).Append('\n');
            if (material is not null) _text.Append("usemtl ").Append(material).Append('\n');
        }

        private void Vertex(float x, float y, float z)
        {
            _points.Add((x, y, z));
            _text.Append("v ").Append(F(x)).Append(' ').Append(F(y)).Append(' ').Append(F(z)).Append('\n');
        }

        private void Quad((float X, float Y, float Z) inside, int a, int b, int c, int d)
        {
            Triangle(inside, a, b, c);
            Triangle(inside, a, c, d);
        }

        private void Triangle((float X, float Y, float Z) inside, int a, int b, int c)
        {
            ((float X, float Y, float Z) pa, (float X, float Y, float Z) pb, (float X, float Y, float Z) pc) = (_points[a], _points[b], _points[c]);
            float ux = pb.X - pa.X, uy = pb.Y - pa.Y, uz = pb.Z - pa.Z;
            float vx = pc.X - pa.X, vy = pc.Y - pa.Y, vz = pc.Z - pa.Z;
            float nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
            float ox = (pa.X + pb.X + pc.X) / 3f - inside.X;
            float oy = (pa.Y + pb.Y + pc.Y) / 3f - inside.Y;
            float oz = (pa.Z + pb.Z + pc.Z) / 3f - inside.Z;
            if (nx * ox + ny * oy + nz * oz < 0f)
                (b, c) = (c, b);
            _text.Append("f ").Append(a + 1).Append(' ').Append(b + 1).Append(' ').Append(c + 1).Append('\n');
        }

        /// <summary>Four decimals at most, invariant, never "-0", so a regeneration is byte-identical.</summary>
        private static string F(float value)
        {
            double rounded = Math.Round(value, 4, MidpointRounding.AwayFromZero);
            if (rounded == 0) rounded = 0;
            return rounded.ToString("0.####", CultureInfo.InvariantCulture);
        }
    }
}
