using System.Globalization;
using System.Text;

namespace Avalon.ChunkGen;

/// <summary>
/// Writes a piece as chunk-local OBJ (x/z 0-30, y up), the format ChunkLayoutNavmeshBuilder and the client bake read:
/// "o", "v x y z" and "f a b c" lines only, LF line ends. Every face is wound so (b-a)x(c-a) points out of its solid,
/// which is how Recast tells a walkable top from a wall.
/// </summary>
public static class ObjWriter
{
    public static string Write(ChunkPiece piece)
    {
        var obj = new ObjBuilder();
        obj.Box("Floor", 0f, ChunkPiece.CellSize, -ChunkPiece.FloorThickness, 0f, 0f, ChunkPiece.CellSize);

        int n = 1;
        foreach (Blocker blocker in piece.Blockers)
        {
            string name = $"Blocker_{n++}";
            switch (blocker)
            {
                case BoxBlocker box:
                    obj.Box(name, box.MinX, box.MaxX, 0f, ChunkPiece.BlockerHeight, box.MinZ, box.MaxZ);
                    break;
                case CylinderBlocker cylinder:
                    obj.Cylinder(name, cylinder.X, cylinder.Z, cylinder.Radius, ChunkPiece.BlockerHeight);
                    break;
            }
        }

        return $"# Avalon chunk: {piece.Name}\n# Generated by tools/Avalon.ChunkGen; regenerate it rather than editing it by hand\n{obj}";
    }

    private sealed class ObjBuilder
    {
        private readonly StringBuilder _text = new();
        private readonly List<(float X, float Y, float Z)> _points = [];

        public void Box(string name, float x0, float x1, float y0, float y1, float z0, float z1)
        {
            _text.Append("o ").Append(name).Append('\n');
            int b = _points.Count;
            Vertex(x0, y0, z0); Vertex(x1, y0, z0); Vertex(x1, y0, z1); Vertex(x0, y0, z1);
            Vertex(x0, y1, z0); Vertex(x1, y1, z0); Vertex(x1, y1, z1); Vertex(x0, y1, z1);
            var inside = ((x0 + x1) / 2f, (y0 + y1) / 2f, (z0 + z1) / 2f);
            Quad(inside, b + 4, b + 5, b + 6, b + 7);   // top
            Quad(inside, b + 0, b + 1, b + 2, b + 3);   // bottom
            Quad(inside, b + 0, b + 1, b + 5, b + 4);   // z0 side
            Quad(inside, b + 3, b + 2, b + 6, b + 7);   // z1 side
            Quad(inside, b + 0, b + 3, b + 7, b + 4);   // x0 side
            Quad(inside, b + 1, b + 2, b + 6, b + 5);   // x1 side
        }

        public void Cylinder(string name, float x, float z, float radius, float height)
        {
            _text.Append("o ").Append(name).Append('\n');
            int b = _points.Count;
            const int n = CylinderBlocker.Segments;
            for (int i = 0; i < n; i++)
            {
                double angle = 2.0 * Math.PI * i / n;
                Vertex(x + (float)(radius * Math.Cos(angle)), 0f, z + (float)(radius * Math.Sin(angle)));
            }
            for (int i = 0; i < n; i++)
            {
                double angle = 2.0 * Math.PI * i / n;
                Vertex(x + (float)(radius * Math.Cos(angle)), height, z + (float)(radius * Math.Sin(angle)));
            }
            int bottomCentre = _points.Count;
            Vertex(x, 0f, z);
            int topCentre = _points.Count;
            Vertex(x, height, z);

            var inside = (x, height / 2f, z);
            for (int i = 0; i < n; i++)
            {
                int j = (i + 1) % n;
                Triangle(inside, topCentre, b + n + i, b + n + j);
                Triangle(inside, bottomCentre, b + i, b + j);
                Quad(inside, b + i, b + j, b + n + j, b + n + i);
            }
        }

        public override string ToString() => _text.ToString();

        private void Vertex(float x, float y, float z)
        {
            _points.Add((x, y, z));
            _text.Append("v ").Append(F(x)).Append(' ').Append(F(y)).Append(' ').Append(F(z)).Append('\n');
        }

        private void Quad((float X, float Y, float Z) inside, int a, int b, int c, int d)
        {
            Triangle(inside, a, b, c);
            Triangle(inside, a, c, d);
        }

        private void Triangle((float X, float Y, float Z) inside, int a, int b, int c)
        {
            var (pa, pb, pc) = (_points[a], _points[b], _points[c]);
            float ux = pb.X - pa.X, uy = pb.Y - pa.Y, uz = pb.Z - pa.Z;
            float vx = pc.X - pa.X, vy = pc.Y - pa.Y, vz = pc.Z - pa.Z;
            float nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
            float ox = (pa.X + pb.X + pc.X) / 3f - inside.X;
            float oy = (pa.Y + pb.Y + pc.Y) / 3f - inside.Y;
            float oz = (pa.Z + pb.Z + pc.Z) / 3f - inside.Z;
            if (nx * ox + ny * oy + nz * oz < 0f)
                (b, c) = (c, b);
            _text.Append("f ").Append(a + 1).Append(' ').Append(b + 1).Append(' ').Append(c + 1).Append('\n');
        }

        /// <summary>Four decimals at most, invariant, never "-0", so a regeneration is byte-identical.</summary>
        private static string F(float value)
        {
            double rounded = Math.Round(value, 4, MidpointRounding.AwayFromZero);
            if (rounded == 0) rounded = 0;
            return rounded.ToString("0.####", CultureInfo.InvariantCulture);
        }
    }
}
