// <auto-generated />
using System;
using Avalon.Database.Character;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalon.Database.Character.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    [Migration("20240708192758_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.Characters.Character", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("AccountId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("ActionBars")
                        .HasColumnType("int");

                    b.Property<int>("ChosenTitle")
                        .HasColumnType("int");

                    b.Property<ushort>("Class")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("DeleteDate")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Experience")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("InstanceId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLogoutResting")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Latency")
                        .HasColumnType("int");

                    b.Property<ushort>("Level")
                        .HasColumnType("smallint unsigned");

                    b.Property<ulong>("LevelTime")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("LogoutTime")
                        .HasColumnType("int");

                    b.Property<int>("Map")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Power1")
                        .HasColumnType("int");

                    b.Property<int>("Power2")
                        .HasColumnType("int");

                    b.Property<float>("RestBonus")
                        .HasColumnType("float");

                    b.Property<int>("TodayKills")
                        .HasColumnType("int");

                    b.Property<int>("TotalKills")
                        .HasColumnType("int");

                    b.Property<ulong>("TotalTime")
                        .HasColumnType("bigint unsigned");

                    b.Property<float>("X")
                        .HasColumnType("float");

                    b.Property<float>("Y")
                        .HasColumnType("float");

                    b.Property<int>("YesterdayKills")
                        .HasColumnType("int");

                    b.Property<float>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
