// <auto-generated />
using System;
using Avalon.Database.Character;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Avalon.Database.Character.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    [Migration("20260427093813_DropCharacterRunning")]
    partial class DropCharacterRunning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.Characters.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("ActionBars")
                        .HasColumnType("integer");

                    b.Property<int>("ChosenTitle")
                        .HasColumnType("integer");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeleteDate")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Experience")
                        .HasColumnType("numeric(20,0)");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsLogoutResting")
                        .HasColumnType("boolean");

                    b.Property<int>("Latency")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal>("LevelTime")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("LogoutTime")
                        .HasColumnType("integer");

                    b.Property<int>("Map")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Power1")
                        .HasColumnType("integer");

                    b.Property<int>("Power2")
                        .HasColumnType("integer");

                    b.Property<float>("RestBonus")
                        .HasColumnType("real");

                    b.Property<float>("Rotation")
                        .HasColumnType("real");

                    b.Property<int>("TodayKills")
                        .HasColumnType("integer");

                    b.Property<int>("TotalKills")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalTime")
                        .HasColumnType("numeric(20,0)");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.Property<int>("YesterdayKills")
                        .HasColumnType("integer");

                    b.Property<float>("Z")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterInventory", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("Container")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "Container", "Slot");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterInventory");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterSpell", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpellId")
                        .HasColumnType("bigint");

                    b.Property<long>("Cooldown")
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId", "SpellId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterStats", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("AbilityDamage")
                        .HasColumnType("bigint");

                    b.Property<long>("Agility")
                        .HasColumnType("bigint");

                    b.Property<long>("Armor")
                        .HasColumnType("bigint");

                    b.Property<long>("AttackDamage")
                        .HasColumnType("bigint");

                    b.Property<float>("BlockPct")
                        .HasColumnType("real");

                    b.Property<float>("CritPct")
                        .HasColumnType("real");

                    b.Property<float>("DodgePct")
                        .HasColumnType("real");

                    b.Property<long>("Intellect")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxHealth")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxPower1")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxPower2")
                        .HasColumnType("bigint");

                    b.Property<long>("Stamina")
                        .HasColumnType("bigint");

                    b.Property<long>("Strength")
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterInventory", b =>
                {
                    b.HasOne("Avalon.Domain.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterSpell", b =>
                {
                    b.HasOne("Avalon.Domain.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterStats", b =>
                {
                    b.HasOne("Avalon.Domain.Characters.Character", "Character")
                        .WithOne()
                        .HasForeignKey("Avalon.Domain.Characters.CharacterStats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
