// <auto-generated />
using System;
using Avalon.Database.Character;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalon.Database.Character.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    partial class CharacterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.Characters.Character", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("AccountId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("ActionBars")
                        .HasColumnType("int");

                    b.Property<int>("ChosenTitle")
                        .HasColumnType("int");

                    b.Property<ushort>("Class")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("DeleteDate")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Experience")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("InstanceId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLogoutResting")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Latency")
                        .HasColumnType("int");

                    b.Property<ushort>("Level")
                        .HasColumnType("smallint unsigned");

                    b.Property<ulong>("LevelTime")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("LogoutTime")
                        .HasColumnType("int");

                    b.Property<ushort>("Map")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Power1")
                        .HasColumnType("int");

                    b.Property<int>("Power2")
                        .HasColumnType("int");

                    b.Property<float>("RestBonus")
                        .HasColumnType("float");

                    b.Property<float>("Rotation")
                        .HasColumnType("float");

                    b.Property<bool>("Running")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TodayKills")
                        .HasColumnType("int");

                    b.Property<int>("TotalKills")
                        .HasColumnType("int");

                    b.Property<ulong>("TotalTime")
                        .HasColumnType("bigint unsigned");

                    b.Property<float>("X")
                        .HasColumnType("float");

                    b.Property<float>("Y")
                        .HasColumnType("float");

                    b.Property<int>("YesterdayKills")
                        .HasColumnType("int");

                    b.Property<float>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterInventory", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ushort>("Container")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Slot")
                        .HasColumnType("smallint unsigned");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("CharacterId", "Container", "Slot");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterInventory");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterSpell", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("SpellId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Cooldown")
                        .HasColumnType("int unsigned");

                    b.HasKey("CharacterId", "SpellId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterStats", b =>
                {
                    b.Property<ulong>("CharacterId")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("AbilityDamage")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Agility")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Armor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("AttackDamage")
                        .HasColumnType("int unsigned");

                    b.Property<float>("BlockPct")
                        .HasColumnType("float");

                    b.Property<float>("CritPct")
                        .HasColumnType("float");

                    b.Property<float>("DodgePct")
                        .HasColumnType("float");

                    b.Property<uint>("Intellect")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHealth")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxPower1")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxPower2")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Stamina")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Strength")
                        .HasColumnType("int unsigned");

                    b.HasKey("CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterStats", t =>
                        {
                            t.HasCheckConstraint("CK_CharacterStats_MinValues", "MaxHealth >= 0 AND Stamina >= 0 AND Strength >= 0 AND Agility >= 0 AND Intellect >= 0");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterInventory", b =>
                {
                    b.HasOne("Avalon.Domain.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterSpell", b =>
                {
                    b.HasOne("Avalon.Domain.Characters.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Avalon.Domain.Characters.CharacterStats", b =>
                {
                    b.HasOne("Avalon.Domain.Characters.Character", "Character")
                        .WithOne()
                        .HasForeignKey("Avalon.Domain.Characters.CharacterStats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
