CREATE TABLE IF NOT EXISTS `Account` (
    `Id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifier',
    `Username` varchar(32) NOT NULL DEFAULT '',
    `Salt` varbinary(64) NOT NULL,
    `Verifier` varbinary(128) NOT NULL,
    `SessionKey` binary(40) DEFAULT NULL,
    `Email` varchar(120) NOT NULL DEFAULT '',
    `JoinDate` datetime NOT NULL DEFAULT curdate(),
    `LastIp` varchar(36) NOT NULL DEFAULT '127.0.0.1',
    `LastAttemptIp` varchar(36) NOT NULL DEFAULT '127.0.0.1',
    `FailedLogins` int(10) unsigned NOT NULL DEFAULT 0,
    `Locked` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `LastLogin` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `Online` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `MuteTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `MuteReason` varchar(255) NOT NULL DEFAULT '',
    `MuteBy` varchar(32) NOT NULL DEFAULT '',
    `Locale` varchar(16) NOT NULL DEFAULT 'en-US',
    `OS` varchar(3) NOT NULL DEFAULT '',
    `TotalTime` int(10) unsigned NOT NULL DEFAULT 0,
    `Role` varchar(32) NOT NULL DEFAULT 'Player',
    PRIMARY KEY (`Id`),
    UNIQUE KEY `idx_username` (`Username`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Account System';
