// <auto-generated />
using System;
using Avalon.World.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalon.World.Database.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20240721024447_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.World.CharacterCreateInfo", b =>
                {
                    b.Property<ushort>("Class")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Map")
                        .HasColumnType("smallint unsigned");

                    b.Property<float>("Rotation")
                        .HasColumnType("float");

                    b.Property<string>("StartingItems")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StartingSpells")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("X")
                        .HasColumnType("float");

                    b.Property<float>("Y")
                        .HasColumnType("float");

                    b.Property<float>("Z")
                        .HasColumnType("float");

                    b.HasKey("Class");

                    b.ToTable("CharacterCreateInfos");

                    b.HasData(
                        new
                        {
                            Class = (ushort)1,
                            Map = (ushort)1,
                            Rotation = 0f,
                            StartingItems = "1,2,3",
                            StartingSpells = "1",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        },
                        new
                        {
                            Class = (ushort)2,
                            Map = (ushort)1,
                            Rotation = 0f,
                            StartingItems = "1,2",
                            StartingSpells = "2",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        },
                        new
                        {
                            Class = (ushort)3,
                            Map = (ushort)1,
                            Rotation = 0f,
                            StartingItems = "1,2",
                            StartingSpells = "",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        },
                        new
                        {
                            Class = (ushort)4,
                            Map = (ushort)1,
                            Rotation = 0f,
                            StartingItems = "1,2",
                            StartingSpells = "",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.CharacterLevelExperience", b =>
                {
                    b.Property<ushort>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Level"));

                    b.Property<ulong>("Experience")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Level");

                    b.ToTable("CharacterLevelExperiences");

                    b.HasData(
                        new
                        {
                            Level = (ushort)1,
                            Experience = 400ul
                        },
                        new
                        {
                            Level = (ushort)2,
                            Experience = 900ul
                        },
                        new
                        {
                            Level = (ushort)3,
                            Experience = 1400ul
                        },
                        new
                        {
                            Level = (ushort)4,
                            Experience = 2100ul
                        },
                        new
                        {
                            Level = (ushort)5,
                            Experience = 2800ul
                        },
                        new
                        {
                            Level = (ushort)6,
                            Experience = 3600ul
                        },
                        new
                        {
                            Level = (ushort)7,
                            Experience = 4500ul
                        },
                        new
                        {
                            Level = (ushort)8,
                            Experience = 5400ul
                        },
                        new
                        {
                            Level = (ushort)9,
                            Experience = 6500ul
                        },
                        new
                        {
                            Level = (ushort)10,
                            Experience = 7600ul
                        },
                        new
                        {
                            Level = (ushort)11,
                            Experience = 8700ul
                        },
                        new
                        {
                            Level = (ushort)12,
                            Experience = 9800ul
                        },
                        new
                        {
                            Level = (ushort)13,
                            Experience = 11000ul
                        },
                        new
                        {
                            Level = (ushort)14,
                            Experience = 12300ul
                        },
                        new
                        {
                            Level = (ushort)15,
                            Experience = 13600ul
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ClassLevelStat", b =>
                {
                    b.Property<ushort>("Class")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Level")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Agility")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BaseHp")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BaseMana")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Intellect")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Stamina")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Strength")
                        .HasColumnType("int unsigned");

                    b.HasKey("Class", "Level");

                    b.ToTable("ClassLevelStats");

                    b.HasData(
                        new
                        {
                            Class = (ushort)1,
                            Level = (ushort)1,
                            Agility = 20u,
                            BaseHp = 20u,
                            BaseMana = 0u,
                            Intellect = 20u,
                            Stamina = 22u,
                            Strength = 23u
                        },
                        new
                        {
                            Class = (ushort)1,
                            Level = (ushort)2,
                            Agility = 21u,
                            BaseHp = 40u,
                            BaseMana = 0u,
                            Intellect = 20u,
                            Stamina = 24u,
                            Strength = 25u
                        },
                        new
                        {
                            Class = (ushort)1,
                            Level = (ushort)3,
                            Agility = 23u,
                            BaseHp = 60u,
                            BaseMana = 0u,
                            Intellect = 20u,
                            Stamina = 26u,
                            Strength = 27u
                        },
                        new
                        {
                            Class = (ushort)1,
                            Level = (ushort)4,
                            Agility = 24u,
                            BaseHp = 80u,
                            BaseMana = 0u,
                            Intellect = 20u,
                            Stamina = 28u,
                            Strength = 29u
                        },
                        new
                        {
                            Class = (ushort)1,
                            Level = (ushort)5,
                            Agility = 26u,
                            BaseHp = 100u,
                            BaseMana = 0u,
                            Intellect = 20u,
                            Stamina = 30u,
                            Strength = 31u
                        },
                        new
                        {
                            Class = (ushort)2,
                            Level = (ushort)1,
                            Agility = 20u,
                            BaseHp = 16u,
                            BaseMana = 20u,
                            Intellect = 23u,
                            Stamina = 21u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)2,
                            Level = (ushort)2,
                            Agility = 21u,
                            BaseHp = 32u,
                            BaseMana = 40u,
                            Intellect = 25u,
                            Stamina = 22u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)2,
                            Level = (ushort)3,
                            Agility = 22u,
                            BaseHp = 48u,
                            BaseMana = 60u,
                            Intellect = 27u,
                            Stamina = 23u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)2,
                            Level = (ushort)4,
                            Agility = 23u,
                            BaseHp = 64u,
                            BaseMana = 80u,
                            Intellect = 29u,
                            Stamina = 24u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)2,
                            Level = (ushort)5,
                            Agility = 24u,
                            BaseHp = 80u,
                            BaseMana = 100u,
                            Intellect = 31u,
                            Stamina = 25u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)3,
                            Level = (ushort)1,
                            Agility = 23u,
                            BaseHp = 18u,
                            BaseMana = 10u,
                            Intellect = 20u,
                            Stamina = 20u,
                            Strength = 21u
                        },
                        new
                        {
                            Class = (ushort)3,
                            Level = (ushort)2,
                            Agility = 25u,
                            BaseHp = 36u,
                            BaseMana = 20u,
                            Intellect = 20u,
                            Stamina = 21u,
                            Strength = 22u
                        },
                        new
                        {
                            Class = (ushort)3,
                            Level = (ushort)3,
                            Agility = 27u,
                            BaseHp = 54u,
                            BaseMana = 30u,
                            Intellect = 20u,
                            Stamina = 22u,
                            Strength = 23u
                        },
                        new
                        {
                            Class = (ushort)3,
                            Level = (ushort)4,
                            Agility = 29u,
                            BaseHp = 72u,
                            BaseMana = 40u,
                            Intellect = 20u,
                            Stamina = 23u,
                            Strength = 24u
                        },
                        new
                        {
                            Class = (ushort)3,
                            Level = (ushort)5,
                            Agility = 31u,
                            BaseHp = 90u,
                            BaseMana = 50u,
                            Intellect = 20u,
                            Stamina = 24u,
                            Strength = 25u
                        },
                        new
                        {
                            Class = (ushort)4,
                            Level = (ushort)1,
                            Agility = 21u,
                            BaseHp = 18u,
                            BaseMana = 20u,
                            Intellect = 23u,
                            Stamina = 20u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)4,
                            Level = (ushort)2,
                            Agility = 22u,
                            BaseHp = 36u,
                            BaseMana = 40u,
                            Intellect = 25u,
                            Stamina = 21u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)4,
                            Level = (ushort)3,
                            Agility = 23u,
                            BaseHp = 54u,
                            BaseMana = 60u,
                            Intellect = 27u,
                            Stamina = 22u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)4,
                            Level = (ushort)4,
                            Agility = 24u,
                            BaseHp = 72u,
                            BaseMana = 80u,
                            Intellect = 29u,
                            Stamina = 23u,
                            Strength = 20u
                        },
                        new
                        {
                            Class = (ushort)4,
                            Level = (ushort)5,
                            Agility = 25u,
                            BaseHp = 90u,
                            BaseMana = 100u,
                            Intellect = 31u,
                            Stamina = 24u,
                            Strength = 20u
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.CreatureTemplate", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AIName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("ArmorModifier")
                        .HasColumnType("float");

                    b.Property<int>("BaseAttackTime")
                        .HasColumnType("int");

                    b.Property<float>("DamageModifier")
                        .HasColumnType("float");

                    b.Property<float>("DetectionRange")
                        .HasColumnType("float");

                    b.Property<short>("DmgSchool")
                        .HasColumnType("smallint");

                    b.Property<short>("Exp")
                        .HasColumnType("smallint");

                    b.Property<float>("ExperienceModifier")
                        .HasColumnType("float");

                    b.Property<ushort>("Family")
                        .HasColumnType("smallint unsigned");

                    b.Property<float>("HealthModifier")
                        .HasColumnType("float");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LootId")
                        .HasColumnType("int");

                    b.Property<float>("ManaModifier")
                        .HasColumnType("float");

                    b.Property<int>("MaxGold")
                        .HasColumnType("int");

                    b.Property<short>("MaxLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("MinGold")
                        .HasColumnType("int");

                    b.Property<short>("MinLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<short>("MovementType")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RangeAttackTime")
                        .HasColumnType("int");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<short>("RegenHealth")
                        .HasColumnType("smallint");

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("SpeedRun")
                        .HasColumnType("float");

                    b.Property<float>("SpeedSwim")
                        .HasColumnType("float");

                    b.Property<float>("SpeedWalk")
                        .HasColumnType("float");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("CreatureTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Exp = (short)0,
                            ExperienceModifier = 1f,
                            Family = (ushort)0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Uriel",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            ScriptName = "UrielTownPatrolScript",
                            SpeedRun = 5f,
                            SpeedSwim = 1.6f,
                            SpeedWalk = 2f,
                            SubName = "",
                            Type = (ushort)7
                        },
                        new
                        {
                            Id = 2ul,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Exp = (short)0,
                            ExperienceModifier = 1f,
                            Family = (ushort)0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Borin Stoutbeard",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            ScriptName = "UrielPathfinderScript",
                            SpeedRun = 5f,
                            SpeedSwim = 1.6f,
                            SpeedWalk = 2f,
                            SubName = "",
                            Type = (ushort)7
                        },
                        new
                        {
                            Id = 3ul,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Exp = (short)0,
                            ExperienceModifier = 1f,
                            Family = (ushort)0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Innkeeper",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            ScriptName = "",
                            SpeedRun = 5f,
                            SpeedSwim = 1.6f,
                            SpeedWalk = 2f,
                            SubName = "",
                            Type = (ushort)7
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<uint>("CharacterId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Charges")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Count")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Durability")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<ulong>("TemplateId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("Avalon.Domain.World.ItemTemplate", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AllowedClasses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("BuyPrice")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<uint?>("DamageMax1")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DamageMax2")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DamageMin1")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("DamageMin2")
                        .HasColumnType("int unsigned");

                    b.Property<int?>("DamageType1")
                        .HasColumnType("int");

                    b.Property<int?>("DamageType2")
                        .HasColumnType("int");

                    b.Property<uint>("DisplayId")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<ushort?>("ItemPower")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("MaxStackSize")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<ushort?>("RequiredLevel")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("SellPrice")
                        .HasColumnType("int unsigned");

                    b.Property<ushort?>("Slot")
                        .HasColumnType("smallint unsigned");

                    b.Property<int?>("StatType1")
                        .HasColumnType("int");

                    b.Property<int?>("StatType10")
                        .HasColumnType("int");

                    b.Property<int?>("StatType2")
                        .HasColumnType("int");

                    b.Property<int?>("StatType3")
                        .HasColumnType("int");

                    b.Property<int?>("StatType4")
                        .HasColumnType("int");

                    b.Property<int?>("StatType5")
                        .HasColumnType("int");

                    b.Property<int?>("StatType6")
                        .HasColumnType("int");

                    b.Property<int?>("StatType7")
                        .HasColumnType("int");

                    b.Property<int?>("StatType8")
                        .HasColumnType("int");

                    b.Property<int?>("StatType9")
                        .HasColumnType("int");

                    b.Property<uint?>("StatValue1")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue10")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue2")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue3")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue4")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue5")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue6")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue7")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue8")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("StatValue9")
                        .HasColumnType("int unsigned");

                    b.Property<int>("SubClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            AllowedClasses = "Warrior,Wizard,Hunter,Healer",
                            BuyPrice = 10u,
                            Class = 0,
                            DisplayId = 1u,
                            Flags = 256,
                            MaxStackSize = 40u,
                            Name = "Health Potion",
                            Rarity = 1,
                            SellPrice = 5u,
                            SubClass = 0
                        },
                        new
                        {
                            Id = 2ul,
                            AllowedClasses = "Warrior,Wizard,Hunter,Healer",
                            BuyPrice = 13u,
                            Class = 0,
                            DisplayId = 2u,
                            Flags = 256,
                            MaxStackSize = 40u,
                            Name = "Mana Potion",
                            Rarity = 1,
                            SellPrice = 6u,
                            SubClass = 0
                        },
                        new
                        {
                            Id = 3ul,
                            AllowedClasses = "Warrior,Wizard,Hunter,Healer",
                            BuyPrice = 100u,
                            Class = 0,
                            DisplayId = 3u,
                            Flags = 256,
                            MaxStackSize = 40u,
                            Name = "Town Portal Scroll",
                            Rarity = 1,
                            SellPrice = 50u,
                            SubClass = 2
                        },
                        new
                        {
                            Id = 4ul,
                            AllowedClasses = "Warrior",
                            BuyPrice = 100u,
                            Class = 1,
                            DamageMax1 = 3u,
                            DamageMin1 = 1u,
                            DamageType1 = 0,
                            DisplayId = 4u,
                            Flags = 256,
                            ItemPower = (ushort)2,
                            MaxStackSize = 1u,
                            Name = "Rusted Sword",
                            Rarity = 1,
                            RequiredLevel = (ushort)1,
                            SellPrice = 50u,
                            Slot = (ushort)9,
                            StatType1 = 12,
                            StatValue1 = 13u,
                            SubClass = 100
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.MapTemplate", b =>
                {
                    b.Property<ushort>("Id")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("AreaTableId")
                        .HasColumnType("int");

                    b.Property<float?>("CorpseX")
                        .HasColumnType("float");

                    b.Property<float?>("CorpseY")
                        .HasColumnType("float");

                    b.Property<float?>("CorpseZ")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InstanceType")
                        .HasColumnType("int");

                    b.Property<int>("LoadingScreenId")
                        .HasColumnType("int");

                    b.Property<ushort?>("MaxLevel")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("MaxPlayers")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("MinLevel")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PvP")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("MapTemplates");

                    b.HasData(
                        new
                        {
                            Id = (ushort)1,
                            AreaTableId = 0,
                            CorpseX = 0f,
                            CorpseY = 0f,
                            Description = "Glimmerdell",
                            Directory = "Maps/",
                            InstanceType = 0,
                            LoadingScreenId = 0,
                            MaxLevel = (ushort)60,
                            MaxPlayers = (ushort)32,
                            MinLevel = (ushort)1,
                            Name = "world.bin",
                            PvP = false
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestReward", b =>
                {
                    b.Property<uint>("QuestId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RewardId")
                        .HasColumnType("int unsigned");

                    b.HasKey("QuestId", "RewardId");

                    b.HasIndex("RewardId");

                    b.ToTable("QuestRewards");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestRewardTemplate", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("Count")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Value")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("QuestRewardTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestTemplate", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<int>("ClassRequirement")
                        .HasColumnType("int");

                    b.Property<int>("CompletionCriteriaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EnderCreatureId")
                        .HasColumnType("int");

                    b.Property<ushort>("Environment")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("GiverCreatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int");

                    b.Property<ushort>("Rarity")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("RepeatFrequency")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("RequiredQuestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("QuestTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.SpellTemplate", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("AllowedClasses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("CastTime")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Cooldown")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Cost")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("EffectValue")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Effects")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Range")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("SpellTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            AllowedClasses = "[1]",
                            CastTime = 0u,
                            Cooldown = 2500u,
                            Cost = 25u,
                            EffectValue = 10u,
                            Effects = (ushort)1,
                            Name = "Strike",
                            Range = (ushort)1
                        },
                        new
                        {
                            Id = 2u,
                            AllowedClasses = "[2]",
                            CastTime = 1000u,
                            Cooldown = 1000u,
                            Cost = 10u,
                            EffectValue = 10u,
                            Effects = (ushort)1,
                            Name = "Lightning Bolt",
                            Range = (ushort)10
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ItemInstance", b =>
                {
                    b.HasOne("Avalon.Domain.World.ItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestReward", b =>
                {
                    b.HasOne("Avalon.Domain.World.QuestTemplate", "Quest")
                        .WithMany("Rewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalon.Domain.World.QuestRewardTemplate", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestTemplate", b =>
                {
                    b.Navigation("Rewards");
                });
#pragma warning restore 612, 618
        }
    }
}
