// <auto-generated />
using System;
using Avalon.Database.World;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Avalon.Database.World.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260428130243_ExpandForestPool")]
    partial class ExpandForestPool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.World.CharacterCreateInfo", b =>
                {
                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<int>("Map")
                        .HasColumnType("integer");

                    b.Property<float>("Rotation")
                        .HasColumnType("real");

                    b.Property<string>("StartingItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartingSpells")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.Property<float>("Z")
                        .HasColumnType("real");

                    b.HasKey("Class");

                    b.ToTable("CharacterCreateInfos");

                    b.HasData(
                        new
                        {
                            Class = 1,
                            Map = 1,
                            Rotation = 0f,
                            StartingItems = "1,2,3",
                            StartingSpells = "1,2",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        },
                        new
                        {
                            Class = 2,
                            Map = 1,
                            Rotation = 0f,
                            StartingItems = "1,2",
                            StartingSpells = "2",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        },
                        new
                        {
                            Class = 3,
                            Map = 1,
                            Rotation = 0f,
                            StartingItems = "1,2",
                            StartingSpells = "",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        },
                        new
                        {
                            Class = 4,
                            Map = 1,
                            Rotation = 0f,
                            StartingItems = "1,2",
                            StartingSpells = "",
                            X = 25f,
                            Y = 51f,
                            Z = 25f
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.CharacterLevelExperience", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Level"));

                    b.Property<decimal>("Experience")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Level");

                    b.ToTable("CharacterLevelExperiences");

                    b.HasData(
                        new
                        {
                            Level = 1,
                            Experience = 400m
                        },
                        new
                        {
                            Level = 2,
                            Experience = 900m
                        },
                        new
                        {
                            Level = 3,
                            Experience = 1400m
                        },
                        new
                        {
                            Level = 4,
                            Experience = 2100m
                        },
                        new
                        {
                            Level = 5,
                            Experience = 2800m
                        },
                        new
                        {
                            Level = 6,
                            Experience = 3600m
                        },
                        new
                        {
                            Level = 7,
                            Experience = 4500m
                        },
                        new
                        {
                            Level = 8,
                            Experience = 5400m
                        },
                        new
                        {
                            Level = 9,
                            Experience = 6500m
                        },
                        new
                        {
                            Level = 10,
                            Experience = 7600m
                        },
                        new
                        {
                            Level = 11,
                            Experience = 8700m
                        },
                        new
                        {
                            Level = 12,
                            Experience = 9800m
                        },
                        new
                        {
                            Level = 13,
                            Experience = 11000m
                        },
                        new
                        {
                            Level = 14,
                            Experience = 12300m
                        },
                        new
                        {
                            Level = 15,
                            Experience = 13600m
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ChunkPool", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChunkPools");
                });

            modelBuilder.Entity("Avalon.Domain.World.ChunkPoolMembership", b =>
                {
                    b.Property<int>("ChunkPoolId")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkTemplateId")
                        .HasColumnType("integer");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ChunkPoolId", "ChunkTemplateId");

                    b.HasIndex("ChunkTemplateId");

                    b.ToTable("ChunkPoolMembership");
                });

            modelBuilder.Entity("Avalon.Domain.World.ChunkTemplate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("CellFootprintX")
                        .HasColumnType("smallint");

                    b.Property<byte>("CellFootprintZ")
                        .HasColumnType("smallint");

                    b.Property<float>("CellSize")
                        .HasColumnType("real");

                    b.Property<int>("Exits")
                        .HasColumnType("integer");

                    b.Property<string>("GeometryFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChunkTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.ClassLevelStat", b =>
                {
                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("Agility")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseHp")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseMana")
                        .HasColumnType("bigint");

                    b.Property<long>("Intellect")
                        .HasColumnType("bigint");

                    b.Property<long>("Stamina")
                        .HasColumnType("bigint");

                    b.Property<long>("Strength")
                        .HasColumnType("bigint");

                    b.HasKey("Class", "Level");

                    b.ToTable("ClassLevelStats");

                    b.HasData(
                        new
                        {
                            Class = 1,
                            Level = 1,
                            Agility = 20L,
                            BaseHp = 20L,
                            BaseMana = 0L,
                            Intellect = 20L,
                            Stamina = 22L,
                            Strength = 23L
                        },
                        new
                        {
                            Class = 1,
                            Level = 2,
                            Agility = 21L,
                            BaseHp = 40L,
                            BaseMana = 0L,
                            Intellect = 20L,
                            Stamina = 24L,
                            Strength = 25L
                        },
                        new
                        {
                            Class = 1,
                            Level = 3,
                            Agility = 23L,
                            BaseHp = 60L,
                            BaseMana = 0L,
                            Intellect = 20L,
                            Stamina = 26L,
                            Strength = 27L
                        },
                        new
                        {
                            Class = 1,
                            Level = 4,
                            Agility = 24L,
                            BaseHp = 80L,
                            BaseMana = 0L,
                            Intellect = 20L,
                            Stamina = 28L,
                            Strength = 29L
                        },
                        new
                        {
                            Class = 1,
                            Level = 5,
                            Agility = 26L,
                            BaseHp = 100L,
                            BaseMana = 0L,
                            Intellect = 20L,
                            Stamina = 30L,
                            Strength = 31L
                        },
                        new
                        {
                            Class = 2,
                            Level = 1,
                            Agility = 20L,
                            BaseHp = 16L,
                            BaseMana = 20L,
                            Intellect = 23L,
                            Stamina = 21L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 2,
                            Level = 2,
                            Agility = 21L,
                            BaseHp = 32L,
                            BaseMana = 40L,
                            Intellect = 25L,
                            Stamina = 22L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 2,
                            Level = 3,
                            Agility = 22L,
                            BaseHp = 48L,
                            BaseMana = 60L,
                            Intellect = 27L,
                            Stamina = 23L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 2,
                            Level = 4,
                            Agility = 23L,
                            BaseHp = 64L,
                            BaseMana = 80L,
                            Intellect = 29L,
                            Stamina = 24L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 2,
                            Level = 5,
                            Agility = 24L,
                            BaseHp = 80L,
                            BaseMana = 100L,
                            Intellect = 31L,
                            Stamina = 25L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 3,
                            Level = 1,
                            Agility = 23L,
                            BaseHp = 18L,
                            BaseMana = 10L,
                            Intellect = 20L,
                            Stamina = 20L,
                            Strength = 21L
                        },
                        new
                        {
                            Class = 3,
                            Level = 2,
                            Agility = 25L,
                            BaseHp = 36L,
                            BaseMana = 20L,
                            Intellect = 20L,
                            Stamina = 21L,
                            Strength = 22L
                        },
                        new
                        {
                            Class = 3,
                            Level = 3,
                            Agility = 27L,
                            BaseHp = 54L,
                            BaseMana = 30L,
                            Intellect = 20L,
                            Stamina = 22L,
                            Strength = 23L
                        },
                        new
                        {
                            Class = 3,
                            Level = 4,
                            Agility = 29L,
                            BaseHp = 72L,
                            BaseMana = 40L,
                            Intellect = 20L,
                            Stamina = 23L,
                            Strength = 24L
                        },
                        new
                        {
                            Class = 3,
                            Level = 5,
                            Agility = 31L,
                            BaseHp = 90L,
                            BaseMana = 50L,
                            Intellect = 20L,
                            Stamina = 24L,
                            Strength = 25L
                        },
                        new
                        {
                            Class = 4,
                            Level = 1,
                            Agility = 21L,
                            BaseHp = 18L,
                            BaseMana = 20L,
                            Intellect = 23L,
                            Stamina = 20L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 4,
                            Level = 2,
                            Agility = 22L,
                            BaseHp = 36L,
                            BaseMana = 40L,
                            Intellect = 25L,
                            Stamina = 21L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 4,
                            Level = 3,
                            Agility = 23L,
                            BaseHp = 54L,
                            BaseMana = 60L,
                            Intellect = 27L,
                            Stamina = 22L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 4,
                            Level = 4,
                            Agility = 24L,
                            BaseHp = 72L,
                            BaseMana = 80L,
                            Intellect = 29L,
                            Stamina = 23L,
                            Strength = 20L
                        },
                        new
                        {
                            Class = 4,
                            Level = 5,
                            Agility = 25L,
                            BaseHp = 90L,
                            BaseMana = 100L,
                            Intellect = 31L,
                            Stamina = 24L,
                            Strength = 20L
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.CreatureTemplate", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("AIName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ArmorModifier")
                        .HasColumnType("real");

                    b.Property<int>("BaseAttackTime")
                        .HasColumnType("integer");

                    b.Property<int>("BodyRemoveTimerSecs")
                        .HasColumnType("integer");

                    b.Property<float>("DamageModifier")
                        .HasColumnType("real");

                    b.Property<float>("DetectionRange")
                        .HasColumnType("real");

                    b.Property<short>("DmgSchool")
                        .HasColumnType("smallint");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("Exp");

                    b.Property<float>("ExperienceModifier")
                        .HasColumnType("real");

                    b.Property<int>("Family")
                        .HasColumnType("integer");

                    b.Property<float>("HealthModifier")
                        .HasColumnType("real");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LootId")
                        .HasColumnType("integer");

                    b.Property<float>("ManaModifier")
                        .HasColumnType("real");

                    b.Property<int>("MaxGold")
                        .HasColumnType("integer");

                    b.Property<short>("MaxLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("MinGold")
                        .HasColumnType("integer");

                    b.Property<short>("MinLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("MovementId")
                        .HasColumnType("integer");

                    b.Property<short>("MovementType")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RangeAttackTime")
                        .HasColumnType("integer");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<short>("RegenHealth")
                        .HasColumnType("smallint");

                    b.Property<int>("RespawnTimerSecs")
                        .HasColumnType("integer");

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("SpeedRun")
                        .HasColumnType("real");

                    b.Property<float>("SpeedSwim")
                        .HasColumnType("real");

                    b.Property<float>("SpeedWalk")
                        .HasColumnType("real");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CreatureTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            BodyRemoveTimerSecs = 120,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Experience = 20L,
                            ExperienceModifier = 1f,
                            Family = 0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Uriel",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            RespawnTimerSecs = 180,
                            ScriptName = "UrielTownPatrolScript",
                            SpeedRun = 5f,
                            SpeedSwim = 1.6f,
                            SpeedWalk = 2f,
                            SubName = "",
                            Type = 7
                        },
                        new
                        {
                            Id = 2m,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            BodyRemoveTimerSecs = 120,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Experience = 20L,
                            ExperienceModifier = 1f,
                            Family = 0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Borin Stoutbeard",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            RespawnTimerSecs = 180,
                            ScriptName = "UrielPathfinderScript",
                            SpeedRun = 5f,
                            SpeedSwim = 1.6f,
                            SpeedWalk = 2f,
                            SubName = "",
                            Type = 7
                        },
                        new
                        {
                            Id = 3m,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            BodyRemoveTimerSecs = 120,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Experience = 20L,
                            ExperienceModifier = 1f,
                            Family = 0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Innkeeper",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            RespawnTimerSecs = 180,
                            ScriptName = "",
                            SpeedRun = 5f,
                            SpeedSwim = 1.6f,
                            SpeedWalk = 2f,
                            SubName = "",
                            Type = 7
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("Charges")
                        .HasColumnType("bigint");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<long>("Durability")
                        .HasColumnType("bigint");

                    b.Property<int>("Flags")
                        .HasColumnType("integer");

                    b.Property<decimal>("TemplateId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("Avalon.Domain.World.ItemTemplate", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("AllowedClasses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BuyPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<long?>("DamageMax1")
                        .HasColumnType("bigint");

                    b.Property<long?>("DamageMax2")
                        .HasColumnType("bigint");

                    b.Property<long?>("DamageMin1")
                        .HasColumnType("bigint");

                    b.Property<long?>("DamageMin2")
                        .HasColumnType("bigint");

                    b.Property<int?>("DamageType1")
                        .HasColumnType("integer");

                    b.Property<int?>("DamageType2")
                        .HasColumnType("integer");

                    b.Property<long>("DisplayId")
                        .HasColumnType("bigint");

                    b.Property<int>("Flags")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemPower")
                        .HasColumnType("integer");

                    b.Property<long>("MaxStackSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<long>("SellPrice")
                        .HasColumnType("bigint");

                    b.Property<int?>("Slot")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType1")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType10")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType2")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType3")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType4")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType5")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType6")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType7")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType8")
                        .HasColumnType("integer");

                    b.Property<int?>("StatType9")
                        .HasColumnType("integer");

                    b.Property<long?>("StatValue1")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue10")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue2")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue3")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue4")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue5")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue6")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue7")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue8")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatValue9")
                        .HasColumnType("bigint");

                    b.Property<int>("SubClass")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            AllowedClasses = "Warrior,Wizard,Hunter,Healer",
                            BuyPrice = 10L,
                            Class = 0,
                            DisplayId = 1L,
                            Flags = 256,
                            MaxStackSize = 40L,
                            Name = "Health Potion",
                            Rarity = 1,
                            SellPrice = 5L,
                            SubClass = 0
                        },
                        new
                        {
                            Id = 2m,
                            AllowedClasses = "Warrior,Wizard,Hunter,Healer",
                            BuyPrice = 13L,
                            Class = 0,
                            DisplayId = 2L,
                            Flags = 256,
                            MaxStackSize = 40L,
                            Name = "Mana Potion",
                            Rarity = 1,
                            SellPrice = 6L,
                            SubClass = 0
                        },
                        new
                        {
                            Id = 3m,
                            AllowedClasses = "Warrior,Wizard,Hunter,Healer",
                            BuyPrice = 100L,
                            Class = 0,
                            DisplayId = 3L,
                            Flags = 256,
                            MaxStackSize = 40L,
                            Name = "Town Portal Scroll",
                            Rarity = 1,
                            SellPrice = 50L,
                            SubClass = 2
                        },
                        new
                        {
                            Id = 4m,
                            AllowedClasses = "Warrior",
                            BuyPrice = 100L,
                            Class = 1,
                            DamageMax1 = 3L,
                            DamageMin1 = 1L,
                            DamageType1 = 0,
                            DisplayId = 4L,
                            Flags = 256,
                            ItemPower = 2,
                            MaxStackSize = 1L,
                            Name = "Rusted Sword",
                            Rarity = 1,
                            RequiredLevel = 1,
                            SellPrice = 50L,
                            Slot = 9,
                            StatType1 = 12,
                            StatValue1 = 13L,
                            SubClass = 100
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.MapChunkPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BackPortalTargetMapId")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkTemplateId")
                        .HasColumnType("integer");

                    b.Property<float>("EntryLocalX")
                        .HasColumnType("real");

                    b.Property<float>("EntryLocalY")
                        .HasColumnType("real");

                    b.Property<float>("EntryLocalZ")
                        .HasColumnType("real");

                    b.Property<int?>("ForwardPortalTargetMapId")
                        .HasColumnType("integer");

                    b.Property<short>("GridX")
                        .HasColumnType("smallint");

                    b.Property<short>("GridZ")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsEntry")
                        .HasColumnType("boolean");

                    b.Property<int>("MapTemplateId")
                        .HasColumnType("integer");

                    b.Property<byte>("Rotation")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("MapTemplateId");

                    b.HasIndex("MapTemplateId", "GridX", "GridZ")
                        .IsUnique();

                    b.ToTable("MapChunkPlacements", (string)null);
                });

            modelBuilder.Entity("Avalon.Domain.World.MapTemplate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AreaTableId")
                        .HasColumnType("integer");

                    b.Property<float?>("CorpseX")
                        .HasColumnType("real");

                    b.Property<float?>("CorpseY")
                        .HasColumnType("real");

                    b.Property<float?>("CorpseZ")
                        .HasColumnType("real");

                    b.Property<float>("DefaultSpawnX")
                        .HasColumnType("real");

                    b.Property<float>("DefaultSpawnY")
                        .HasColumnType("real");

                    b.Property<float>("DefaultSpawnZ")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LoadingScreenId")
                        .HasColumnType("integer");

                    b.Property<int?>("LogoutMapId")
                        .HasColumnType("integer");

                    b.Property<int>("MapType")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int?>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PvP")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MapTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaTableId = 0,
                            CorpseX = 0f,
                            CorpseY = 0f,
                            DefaultSpawnX = 25f,
                            DefaultSpawnY = 51f,
                            DefaultSpawnZ = 25f,
                            Description = "Glimmerdell",
                            LoadingScreenId = 0,
                            MapType = 0,
                            MaxLevel = 60,
                            MaxPlayers = 30,
                            MinLevel = 1,
                            Name = "world.bin",
                            PvP = false
                        },
                        new
                        {
                            Id = 2,
                            AreaTableId = 0,
                            DefaultSpawnX = 0f,
                            DefaultSpawnY = 0f,
                            DefaultSpawnZ = 0f,
                            Description = "Forest Dungeon",
                            LoadingScreenId = 0,
                            LogoutMapId = 1,
                            MapType = 1,
                            MaxLevel = 10,
                            MaxPlayers = 1,
                            MinLevel = 1,
                            Name = "ForestDungeon",
                            PvP = false
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ProceduralMapConfig", b =>
                {
                    b.Property<int>("MapTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("BackPortalTargetMapId")
                        .HasColumnType("integer");

                    b.Property<float>("BranchChance")
                        .HasColumnType("real");

                    b.Property<byte>("BranchMaxDepth")
                        .HasColumnType("smallint");

                    b.Property<int>("ChunkPoolId")
                        .HasColumnType("integer");

                    b.Property<int?>("ForwardPortalTargetMapId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBoss")
                        .HasColumnType("boolean");

                    b.Property<int>("MainPathMax")
                        .HasColumnType("integer");

                    b.Property<int>("MainPathMin")
                        .HasColumnType("integer");

                    b.Property<int>("SpawnTableId")
                        .HasColumnType("integer");

                    b.HasKey("MapTemplateId");

                    b.ToTable("ProceduralMapConfigs");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestReward", b =>
                {
                    b.Property<long>("QuestId")
                        .HasColumnType("bigint");

                    b.Property<long>("RewardId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestId", "RewardId");

                    b.HasIndex("RewardId");

                    b.ToTable("QuestRewards");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestRewardTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("QuestRewardTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClassRequirement")
                        .HasColumnType("integer");

                    b.Property<int>("CompletionCriteriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnderCreatureId")
                        .HasColumnType("integer");

                    b.Property<int>("Environment")
                        .HasColumnType("integer");

                    b.Property<int>("GiverCreatureId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int?>("RepeatFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredQuestId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuestTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.SpawnTable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpawnTables");
                });

            modelBuilder.Entity("Avalon.Domain.World.SpellTemplate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<int[]>("AllowedClasses")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<long>("CastTime")
                        .HasColumnType("bigint");

                    b.Property<long>("Cooldown")
                        .HasColumnType("bigint");

                    b.Property<long>("Cost")
                        .HasColumnType("bigint");

                    b.Property<long>("EffectValue")
                        .HasColumnType("bigint");

                    b.Property<int>("Effects")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Range")
                        .HasColumnType("integer");

                    b.Property<string>("SpellScript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpellTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AllowedClasses = new[] { 1 },
                            CastTime = 0L,
                            Cooldown = 2500L,
                            Cost = 25L,
                            EffectValue = 10L,
                            Effects = 1,
                            Name = "Strike",
                            Range = 1,
                            SpellScript = "StrikeSpellScript"
                        },
                        new
                        {
                            Id = 2L,
                            AllowedClasses = new[] { 1, 2 },
                            CastTime = 2000L,
                            Cooldown = 1000L,
                            Cost = 10L,
                            EffectValue = 10L,
                            Effects = 1,
                            Name = "Fireball",
                            Range = 10,
                            SpellScript = "FireballSpellScript"
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ChunkPoolMembership", b =>
                {
                    b.HasOne("Avalon.Domain.World.ChunkPool", "Pool")
                        .WithMany("Memberships")
                        .HasForeignKey("ChunkPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalon.Domain.World.ChunkTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("ChunkTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Avalon.Domain.World.ChunkTemplate", b =>
                {
                    b.OwnsMany("Avalon.Domain.World.ChunkPortalSlot", "PortalSlots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ChunkTemplateId")
                                .HasColumnType("integer");

                            b1.Property<float>("LocalX")
                                .HasColumnType("real");

                            b1.Property<float>("LocalY")
                                .HasColumnType("real");

                            b1.Property<float>("LocalZ")
                                .HasColumnType("real");

                            b1.Property<byte>("Role")
                                .HasColumnType("smallint");

                            b1.HasKey("Id");

                            b1.HasIndex("ChunkTemplateId");

                            b1.ToTable("ChunkPortalSlot");

                            b1.WithOwner()
                                .HasForeignKey("ChunkTemplateId");
                        });

                    b.OwnsMany("Avalon.Domain.World.ChunkSpawnSlot", "SpawnSlots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ChunkTemplateId")
                                .HasColumnType("integer");

                            b1.Property<float>("LocalX")
                                .HasColumnType("real");

                            b1.Property<float>("LocalY")
                                .HasColumnType("real");

                            b1.Property<float>("LocalZ")
                                .HasColumnType("real");

                            b1.Property<string>("Tag")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("ChunkTemplateId");

                            b1.ToTable("ChunkSpawnSlot");

                            b1.WithOwner()
                                .HasForeignKey("ChunkTemplateId");
                        });

                    b.Navigation("PortalSlots");

                    b.Navigation("SpawnSlots");
                });

            modelBuilder.Entity("Avalon.Domain.World.ItemInstance", b =>
                {
                    b.HasOne("Avalon.Domain.World.ItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestReward", b =>
                {
                    b.HasOne("Avalon.Domain.World.QuestTemplate", "Quest")
                        .WithMany("Rewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalon.Domain.World.QuestRewardTemplate", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Avalon.Domain.World.SpawnTable", b =>
                {
                    b.OwnsMany("Avalon.Domain.World.SpawnTableEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("CreatureId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<byte>("MaxCount")
                                .HasColumnType("smallint");

                            b1.Property<byte>("MinCount")
                                .HasColumnType("smallint");

                            b1.Property<int>("SpawnTableId")
                                .HasColumnType("integer");

                            b1.Property<string>("Tag")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<float>("Weight")
                                .HasColumnType("real");

                            b1.HasKey("Id");

                            b1.HasIndex("SpawnTableId");

                            b1.ToTable("SpawnTableEntry");

                            b1.WithOwner()
                                .HasForeignKey("SpawnTableId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Avalon.Domain.World.ChunkPool", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestTemplate", b =>
                {
                    b.Navigation("Rewards");
                });
#pragma warning restore 612, 618
        }
    }
}
