// <auto-generated />
using System;
using Avalon.World.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalon.World.Database.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    partial class WorldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.World.CreatureTemplate", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AIName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("ArmorModifier")
                        .HasColumnType("float");

                    b.Property<int>("BaseAttackTime")
                        .HasColumnType("int");

                    b.Property<float>("DamageModifier")
                        .HasColumnType("float");

                    b.Property<float>("DetectionRange")
                        .HasColumnType("float");

                    b.Property<short>("DmgSchool")
                        .HasColumnType("smallint");

                    b.Property<short>("Exp")
                        .HasColumnType("smallint");

                    b.Property<float>("ExperienceModifier")
                        .HasColumnType("float");

                    b.Property<ushort>("Family")
                        .HasColumnType("smallint unsigned");

                    b.Property<float>("HealthModifier")
                        .HasColumnType("float");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LootId")
                        .HasColumnType("int");

                    b.Property<float>("ManaModifier")
                        .HasColumnType("float");

                    b.Property<int>("MaxGold")
                        .HasColumnType("int");

                    b.Property<short>("MaxLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("MinGold")
                        .HasColumnType("int");

                    b.Property<short>("MinLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<short>("MovementType")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RangeAttackTime")
                        .HasColumnType("int");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<short>("RegenHealth")
                        .HasColumnType("smallint");

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("SpeedRun")
                        .HasColumnType("float");

                    b.Property<float>("SpeedSwim")
                        .HasColumnType("float");

                    b.Property<float>("SpeedWalk")
                        .HasColumnType("float");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("CreatureTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Exp = (short)0,
                            ExperienceModifier = 1f,
                            Family = (ushort)0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Uriel",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            ScriptName = "UrielTownPatrolScript",
                            SpeedRun = 35f,
                            SpeedSwim = 18f,
                            SpeedWalk = 30f,
                            SubName = "",
                            Type = (ushort)7
                        },
                        new
                        {
                            Id = 2ul,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Exp = (short)0,
                            ExperienceModifier = 1f,
                            Family = (ushort)0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Borin Stoutbeard",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            ScriptName = "",
                            SpeedRun = 35f,
                            SpeedSwim = 18f,
                            SpeedWalk = 30f,
                            SubName = "",
                            Type = (ushort)7
                        },
                        new
                        {
                            Id = 3ul,
                            AIName = "",
                            ArmorModifier = 1f,
                            BaseAttackTime = 1,
                            DamageModifier = 1f,
                            DetectionRange = 20f,
                            DmgSchool = (short)0,
                            Exp = (short)0,
                            ExperienceModifier = 1f,
                            Family = (ushort)0,
                            HealthModifier = 1f,
                            IconName = "",
                            LootId = 0,
                            ManaModifier = 1f,
                            MaxGold = 0,
                            MaxLevel = (short)1,
                            MinGold = 0,
                            MinLevel = (short)1,
                            MovementId = 0,
                            MovementType = (short)0,
                            Name = "Innkeeper",
                            RangeAttackTime = 0,
                            Rank = (short)0,
                            RegenHealth = (short)1,
                            ScriptName = "",
                            SpeedRun = 35f,
                            SpeedSwim = 18f,
                            SpeedWalk = 30f,
                            SubName = "",
                            Type = (ushort)7
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.ItemTemplate", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.MapTemplate", b =>
                {
                    b.Property<ushort>("Id")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("AreaTableId")
                        .HasColumnType("int");

                    b.Property<float?>("CorpseX")
                        .HasColumnType("float");

                    b.Property<float?>("CorpseY")
                        .HasColumnType("float");

                    b.Property<float?>("CorpseZ")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InstanceType")
                        .HasColumnType("int");

                    b.Property<int>("LoadingScreenId")
                        .HasColumnType("int");

                    b.Property<ushort?>("MaxLevel")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("MaxPlayers")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("MinLevel")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PvP")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("MapTemplates");

                    b.HasData(
                        new
                        {
                            Id = (ushort)1,
                            AreaTableId = 0,
                            CorpseX = 0f,
                            CorpseY = 0f,
                            Description = "Glimmerdell",
                            Directory = "Maps/",
                            InstanceType = 0,
                            LoadingScreenId = 0,
                            MaxLevel = (ushort)60,
                            MaxPlayers = (ushort)32,
                            MinLevel = (ushort)1,
                            Name = "world.bin",
                            PvP = false
                        });
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestReward", b =>
                {
                    b.Property<uint>("QuestId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RewardId")
                        .HasColumnType("int unsigned");

                    b.HasKey("QuestId", "RewardId");

                    b.HasIndex("RewardId");

                    b.ToTable("QuestRewards");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestRewardTemplate", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("Count")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Value")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("QuestRewardTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestTemplate", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<int>("ClassRequirement")
                        .HasColumnType("int");

                    b.Property<int>("CompletionCriteriaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EnderCreatureId")
                        .HasColumnType("int");

                    b.Property<ushort>("Environment")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("GiverCreatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int");

                    b.Property<ushort>("Rarity")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort?>("RepeatFrequency")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("RequiredQuestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("QuestTemplates");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestReward", b =>
                {
                    b.HasOne("Avalon.Domain.World.QuestTemplate", "Quest")
                        .WithMany("Rewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalon.Domain.World.QuestRewardTemplate", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Avalon.Domain.World.QuestTemplate", b =>
                {
                    b.Navigation("Rewards");
                });
#pragma warning restore 612, 618
        }
    }
}
