apiVersion: v2
name: avalon-api
description: Avalon HTTP API
type: application
# Both are overwritten by the release workflow with the git tag (helm package --version/--app-version).
version: 0.0.0-dev
appVersion: "0.0.0-dev"
