using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Avalon.Domain.World;
using Avalon.World.Public.Enums;

namespace Avalon.Exporter;

/// <summary>
/// Exports what an ItemTemplate is and what its enumerated values mean. The inventory packet
/// carries an ItemTemplateId and a Rarity as bare numbers, so without this a client cannot learn
/// that 3 is Epic -- and a reordered enum would change every item's rarity with nothing to say so.
///
/// Every name and number is read off the types themselves. A transcription would agree with
/// whatever it transcribed, which is the failure this file exists to catch.
/// </summary>
public static class ItemSchema
{
    public const string DirectoryName = "items";
    public const string FileName = "item-schema-v1.json";

    public static string Generate()
    {
        var document = new SchemaDocument(
            Comment: "Generated by tools/Avalon.Exporter -- item-schema. Do not edit by hand. " +
                     "Describes the rows in item-catalog-v1.json and the values the inventory packet carries.",
            Source: "src/Shared/Avalon.Domain/World/ItemTemplate.cs",
            Fields: Fields().ToList(),
            Enums: Vocabularies());

        return JsonSerializer.Serialize(document, Options) + "\n";
    }

    // camelCase, matching opcodes.json — the other code-derived JSON the client reads.
    private static readonly JsonSerializerOptions Options = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    private static IEnumerable<SchemaField> Fields()
    {
        foreach (PropertyInfo property in typeof(ItemTemplate)
                     .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                     .Where(p => p.GetIndexParameters().Length == 0)
                     .OrderBy(p => p.MetadataToken))
        {
            Type type = property.PropertyType;
            Type? nullable = Nullable.GetUnderlyingType(type);
            Type actual = nullable ?? type;

            // A collection is handled here, not inside TypeNameOf: TypeNameOf collapses every enum
            // to the bare string "enum" (so SchemaField.Type stays a small closed vocabulary of
            // wire-level shapes), which is exactly right for a scalar field -- the element's actual
            // vocabulary is reported separately via Enum. But TypeNameOf returns one string for the
            // whole type, so if it also handled List<T> it would have to fold the element's "enum"
            // collapse and the element's vocabulary name into that same string, losing the name.
            // Building the array shape here instead keeps Element (the element's shape) and Enum
            // (the element's vocabulary, when it has one) as separate fields on the same record, so
            // no information is lost and no future collection field needs its own special case.
            if (actual.IsGenericType && actual.GetGenericTypeDefinition() == typeof(List<>))
            {
                Type element = actual.GetGenericArguments()[0];
                yield return new SchemaField(
                    Name: property.Name,
                    Type: "array",
                    Nullable: nullable is not null,
                    Element: TypeNameOf(element),
                    Enum: element.IsEnum ? element.Name : null);
                continue;
            }

            // Nullable means the declaration says the value may be absent: `T?` on a value type.
            // Reference types are not inferred here -- a ValueObject wrapper like ItemTemplateId is
            // a class but is never absent, and saying otherwise would tell the client that a
            // primary key is optional. Name is the one reference type that is null in practice,
            // and the catalog coalesces it to "" rather than describing it as optional.
            yield return new SchemaField(
                Name: property.Name,
                Type: TypeNameOf(actual),
                Nullable: nullable is not null,
                Element: null,
                Enum: actual.IsEnum ? actual.Name : null);
        }
    }

    // Scalar shapes only -- List<T> is handled in Fields(), not here. See the comment there.
    private static string TypeNameOf(Type type)
    {
        if (type.IsEnum) return "enum";
        if (type == typeof(string)) return "string";
        if (type == typeof(bool)) return "bool";
        if (type == typeof(uint)) return "uint32";
        if (type == typeof(ushort)) return "uint16";
        if (type == typeof(ulong)) return "uint64";

        // ValueObject<T> wrappers such as ItemTemplateId report their underlying primitive.
        Type? baseType = type.BaseType;
        while (baseType is not null)
        {
            if (baseType.IsGenericType && baseType.Name.StartsWith("ValueObject", StringComparison.Ordinal))
                return TypeNameOf(baseType.GetGenericArguments()[0]);
            baseType = baseType.BaseType;
        }

        return type.Name;
    }

    private static Dictionary<string, List<EnumValue>> Vocabularies()
    {
        Type[] vocabularies =
        [
            typeof(ItemRarity), typeof(ItemSlotType), typeof(ItemClass),
            typeof(ItemSubClass), typeof(DamageType), typeof(StatType), typeof(ItemTemplateFlags),
            typeof(CharacterClass),
        ];

        return vocabularies.ToDictionary(
            type => type.Name,
            type => Enum.GetNames(type)
                .Select(name => new EnumValue(
                    name,
                    Convert.ToInt64(Enum.Parse(type, name), System.Globalization.CultureInfo.InvariantCulture)))
                .OrderBy(value => value.Value)
                .ThenBy(value => value.Name, StringComparer.Ordinal)
                .ToList());
    }

    private sealed record SchemaDocument(
        [property: JsonPropertyName("$comment")] string Comment,
        string Source,
        List<SchemaField> Fields,
        Dictionary<string, List<EnumValue>> Enums);

    private sealed record SchemaField(string Name, string Type, bool Nullable, string? Element, string? Enum);

    private sealed record EnumValue(string Name, long Value);
}
