// <auto-generated />
using System;
using Avalon.Database.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Avalon.Database.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20261006003325_SharedCommerce")]
    partial class SharedCommerce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.Auth.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CredentialsVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GameplayConsolidationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStoreGenerated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastAttemptIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MuteBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MuteReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("MuteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OnlineSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("SessionEpoch")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("SessionKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("SessionKey");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Email_Normalised", "\"Email\" = lower(trim(\"Email\"))");

                            t.HasCheckConstraint("CK_Accounts_SessionEpoch", "\"SessionEpoch\" >= 0");

                            t.HasCheckConstraint("CK_Accounts_Username_Normalised", "\"Username\" = upper(trim(\"Username\"))");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessLevel = 7,
                            CredentialsVersion = 0,
                            Email = "admin@avalon.monster",
                            FailedLogins = 0,
                            IsStoreGenerated = false,
                            JoinDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastAttemptIp = "",
                            LastIp = "127.0.0.1",
                            LastLogin = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Locale = "ptPT",
                            Locked = false,
                            MuteBy = "",
                            MuteReason = "",
                            Online = false,
                            Os = "Linux",
                            Salt = new byte[] { 36, 50, 97, 36, 49, 49, 36, 87, 99, 81, 111, 50, 73, 79, 51, 110, 69, 119, 75, 77, 78, 85, 98, 116, 110, 71, 88, 90, 46 },
                            SessionEpoch = 0L,
                            SessionKey = new byte[0],
                            Status = (byte)0,
                            TotalTime = 0L,
                            Username = "ADMIN",
                            Verifier = new byte[] { 36, 50, 97, 36, 49, 49, 36, 87, 99, 81, 111, 50, 73, 79, 51, 110, 69, 119, 75, 77, 78, 85, 98, 116, 110, 71, 88, 90, 46, 54, 72, 106, 115, 116, 79, 46, 107, 82, 120, 110, 46, 80, 115, 80, 83, 85, 98, 55, 47, 70, 103, 116, 50, 69, 97, 119, 107, 53, 105, 54 }
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AccountConsolidation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedMfaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SourceAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("TargetAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetCredentialsVersion")
                        .HasColumnType("integer");

                    b.Property<long>("TargetSessionEpoch")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("TargetAccountId");

                    b.ToTable("AccountConsolidations");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AccountConsolidationWorld", b =>
                {
                    b.Property<Guid>("ConsolidationId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorldId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuardReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TransferredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransferredCharacters")
                        .HasColumnType("integer");

                    b.HasKey("ConsolidationId", "WorldId");

                    b.ToTable("AccountConsolidationWorlds");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AccountEmailVerification", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CredentialsVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AccountId");

                    b.ToTable("AccountEmailVerifications", t =>
                        {
                            t.HasCheckConstraint("CK_AccountEmailVerifications_Interval", "\"ExpiresAt\" > \"IssuedAt\" AND length(\"TokenHash\") = 64");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AvalonToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUsage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TrustEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Trusted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Provider")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.GameLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("AuthorityRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastObservedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifiedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Environment", "LicenseReference")
                        .IsUnique();

                    b.HasIndex("AccountId", "Product", "Provider", "Environment");

                    b.ToTable("GameLicenses", t =>
                        {
                            t.HasCheckConstraint("CK_GameLicenses_Interval", "(\"ExpiresAt\" IS NULL OR \"ExpiresAt\" > \"GrantedAt\") AND (\"RevokedAt\" IS NULL OR \"RevokedAt\" >= \"GrantedAt\")");

                            t.HasCheckConstraint("CK_GameLicenses_Reference", "length(trim(\"LicenseReference\")) > 0 AND \"LicenseReference\" = trim(\"LicenseReference\")");

                            t.HasCheckConstraint("CK_GameLicenses_Revision", "\"AuthorityRevision\" > 0 AND \"AccountId\" > 0");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.GameSession", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CredentialsVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("FencingToken")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LicenseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousGameSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousServerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("PreviousWorldId")
                        .HasColumnType("integer");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SessionEpoch")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("WorldId")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.ToTable("GameSessions", t =>
                        {
                            t.HasCheckConstraint("CK_GameSessions_FencingToken", "\"FencingToken\" > 0");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.LicenseObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuthorityRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AuthorizedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OwnsProduct")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Permanent")
                        .HasColumnType("boolean");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ProviderExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderOwnerSubject")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("AccountId", "Provider", "ProviderSubject", "Environment", "Product", "ProviderProductId", "ObservedAt");

                    b.ToTable("LicenseObservations");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.MFASetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastAcceptedTotpStep")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RecoveryCode1")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecoveryCode2")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecoveryCode3")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Secret")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("MfaSetups");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.PersonalAccessToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RevokedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "RevokedAt");

                    b.ToTable("PersonalAccessTokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CredentialsVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RotatedByAgentHash")
                        .HasColumnType("bytea");

                    b.Property<string>("RotatedBySource")
                        .HasColumnType("text");

                    b.Property<long>("Usages")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("AccountId", "FamilyId");

                    b.HasIndex("FamilyId", "Index");

                    b.HasIndex("AccountId", "Client", "Revoked");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.StoreAccountCreation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProofExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("StoreAccountCreations");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevelRequired")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("MaintenanceDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MaintenanceEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("MaintenanceRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("MinVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Worlds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevelRequired = 4,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Host = "127.0.0.1",
                            MaintenanceEnabled = false,
                            MaintenanceRevision = 0L,
                            MinVersion = "0.0.1",
                            Name = "Development",
                            Port = 21001,
                            Type = 0,
                            UpdatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = 2,
                            AccessLevelRequired = 1,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Host = "asthoria.avalon.monster",
                            MaintenanceEnabled = false,
                            MaintenanceRevision = 0L,
                            MinVersion = "0.0.1",
                            Name = "Asthoria",
                            Port = 21001,
                            Type = 0,
                            UpdatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = 3,
                            AccessLevelRequired = 32,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Host = "ptr.avalon.monster",
                            MaintenanceEnabled = false,
                            MaintenanceRevision = 0L,
                            MinVersion = "0.0.1",
                            Name = "Public Test Realm",
                            Port = 21001,
                            Type = 0,
                            UpdatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "0.0.1"
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CheckoutEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CheckoutReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstDispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderPriceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ReplayDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SuccessUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Provider", "ProviderAccountId", "Environment", "CheckoutReference")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderAccountId", "Environment", "OperationKey")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderAccountId", "Environment", "PaymentReference")
                        .IsUnique();

                    b.ToTable("PaymentAttempts", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentAttempt_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentDispute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentAttemptId");

                    b.HasIndex("Provider", "ProviderAccountId", "Environment", "ExternalReference")
                        .IsUnique();

                    b.ToTable("PaymentDisputes", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentDispute_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResourceReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentAttemptId");

                    b.HasIndex("State", "NextAttemptAt");

                    b.HasIndex("Provider", "ProviderAccountId", "Environment", "ExternalReference")
                        .IsUnique();

                    b.ToTable("PaymentEvents", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentEvent_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentRefund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("FirstDispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PaymentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReplayDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RequestedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Unresolved")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentAttemptId")
                        .IsUnique()
                        .HasFilter("\"Unresolved\" = TRUE");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("Provider", "ProviderAccountId", "Environment", "ExternalReference")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderAccountId", "Environment", "OperationKey")
                        .IsUnique();

                    b.ToTable("PaymentRefunds", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentRefund_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_PaymentRefunds_Amount", "\"AmountMinor\" > 0 AND length(trim(\"Reason\")) BETWEEN 1 AND 500");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FundingAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("LicenseEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("OriginalPurchaserAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReconciliationIssue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SubtotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long?>("TaxMinor")
                        .HasColumnType("bigint");

                    b.Property<bool>("Unresolved")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FundingAttemptId")
                        .IsUnique();

                    b.HasIndex("LicenseId")
                        .IsUnique();

                    b.HasIndex("OriginalPurchaserAccountId");

                    b.HasIndex("AccountId", "Product", "LicenseEnvironment")
                        .IsUnique()
                        .HasFilter("\"Unresolved\" = TRUE");

                    b.ToTable("PurchaseOrders", t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrder_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_PurchaseOrders_Amount", "\"AmountMinor\" > 0 AND length(\"Currency\") = 3 AND \"Currency\" = lower(\"Currency\")");
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AccountConsolidationWorld", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.AccountConsolidation", null)
                        .WithMany("Worlds")
                        .HasForeignKey("ConsolidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AccountEmailVerification", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AvalonToken", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.Device", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.ExternalIdentity", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Auth.GameLicense", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Auth.GameSession", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithOne()
                        .HasForeignKey("Avalon.Domain.Auth.GameSession", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Auth.LicenseObservation", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avalon.Domain.Auth.GameLicense", null)
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Avalon.Domain.Auth.MFASetup", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.PersonalAccessToken", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentAttempt", b =>
                {
                    b.HasOne("Avalon.Domain.Commerce.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentDispute", b =>
                {
                    b.HasOne("Avalon.Domain.Commerce.PaymentAttempt", null)
                        .WithMany()
                        .HasForeignKey("PaymentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentEvent", b =>
                {
                    b.HasOne("Avalon.Domain.Commerce.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Avalon.Domain.Commerce.PaymentAttempt", null)
                        .WithMany()
                        .HasForeignKey("PaymentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PaymentRefund", b =>
                {
                    b.HasOne("Avalon.Domain.Commerce.PaymentAttempt", null)
                        .WithMany()
                        .HasForeignKey("PaymentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Commerce.PurchaseOrder", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avalon.Domain.Commerce.PaymentAttempt", null)
                        .WithMany()
                        .HasForeignKey("FundingAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Avalon.Domain.Auth.GameLicense", null)
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Avalon.Domain.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("OriginalPurchaserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AccountConsolidation", b =>
                {
                    b.Navigation("Worlds");
                });
#pragma warning restore 612, 618
        }
    }
}
