// <auto-generated />
using System;
using Avalon.Database.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalon.Database.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avalon.Domain.Auth.Account", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ushort>("AccessLevel")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastAttemptIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MuteBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MuteReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MuteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("SessionKey")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("SessionKey");

                    b.Property<long>("TotalTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            AccessLevel = (ushort)3,
                            Email = "admin@avalon.monster",
                            FailedLogins = 0,
                            JoinDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastAttemptIp = "",
                            LastIp = "127.0.0.1",
                            LastLogin = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Locale = "ptPT",
                            Locked = false,
                            MuteBy = "",
                            MuteReason = "",
                            Online = false,
                            Os = "Linux",
                            Salt = new byte[] { 36, 50, 97, 36, 49, 49, 36, 118, 75, 111, 115, 114, 98, 57, 102, 65, 87, 85, 46, 100, 115, 105, 54, 118, 81, 112, 107, 51, 117 },
                            SessionKey = new byte[0],
                            TotalTime = 0L,
                            Username = "ADMIN",
                            Verifier = new byte[] { 36, 50, 97, 36, 49, 49, 36, 118, 75, 111, 115, 114, 98, 57, 102, 65, 87, 85, 46, 100, 115, 105, 54, 118, 81, 112, 107, 51, 117, 116, 87, 81, 107, 87, 68, 98, 90, 113, 71, 111, 102, 71, 104, 113, 78, 74, 56, 75, 57, 89, 75, 111, 47, 52, 118, 98, 77, 70, 47, 83 }
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AvalonToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("LastUsage")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TrustEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Trusted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.MFASetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("RecoveryCode1")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RecoveryCode2")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("RecoveryCode3")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Secret")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<ushort>("Status")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("MfaSetups");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<uint>("Index")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Usages")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.World", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<ushort>("AccessLevelRequired")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MinVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<ushort>("Status")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Worlds");

                    b.HasData(
                        new
                        {
                            Id = (ushort)1,
                            AccessLevelRequired = (ushort)2,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Host = "127.0.0.1",
                            MinVersion = "0.0.1",
                            Name = "Development",
                            Port = 21001,
                            Status = (ushort)1,
                            Type = (ushort)0,
                            UpdatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = (ushort)2,
                            AccessLevelRequired = (ushort)0,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Host = "asthoria.avalon.monster",
                            MinVersion = "0.0.1",
                            Name = "Asthoria",
                            Port = 21001,
                            Status = (ushort)0,
                            Type = (ushort)0,
                            UpdatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = (ushort)3,
                            AccessLevelRequired = (ushort)8,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Host = "ptr.avalon.monster",
                            MinVersion = "0.0.1",
                            Name = "Public Test Realm",
                            Port = 21001,
                            Status = (ushort)0,
                            Type = (ushort)0,
                            UpdatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "0.0.1"
                        });
                });

            modelBuilder.Entity("Avalon.Domain.Auth.AvalonToken", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.Device", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.MFASetup", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Avalon.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("Avalon.Domain.Auth.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
