version: '3.4'
services:
  avalon-server:
    image: registry.nunolevezinho.xyz/avalon/game-server:latest
    container_name: avalon-server
    environment:
      - "AVALON_SERVER__NETWORK__TCP__ENABLED=true"
      - "AVALON_SERVER__NETWORK__TCP__BACKLOG=128"
      - "AVALON_SERVER__NETWORK__UDP__ENABLED=false"
      - "AVALON_SERVER__NETWORK__UDP__BACKLOG=128"
      - "AVALON_SERVER__METRICS__ENABLED=false"
      - "AVALON_SERVER__METRICS__APIURL=localhost"
      - "AVALON_SERVER__METRICS__APIKEY=apiKey"
      - "AVALON_SERVER__METRICS__AUTOMATIC=false"
      - "AVALON_SERVER__METRICS__EXPORT=false"
      - "DATABASE__AUTH__HOST=192.168.1.67"
      - "AVALON_SERVER__DATABASE__AUTH__PORT=3306"
      - "AVALON_SERVER__DATABASE__AUTH__DATABASE=auth"
      - "AVALON_SERVER__DATABASE__AUTH__USERNAME=root"
      - "AVALON_SERVER__DATABASE__AUTH__PASSWORD=123"
      - "DATABASE__CHARACTERS__HOST=192.168.1.67"
      - "AVALON_SERVER__DATABASE__CHARACTERS__PORT=3306"
      - "AVALON_SERVER__DATABASE__CHARACTERS__DATABASE=characters"
      - "AVALON_SERVER__DATABASE__CHARACTERS__USERNAME=root"
      - "AVALON_SERVER__DATABASE__CHARACTERS__PASSWORD=123"
      - "DATABASE__WORLD__HOST=192.168.1.67"
      - "AVALON_SERVER__DATABASE__WORLD__PORT=3306"
      - "AVALON_SERVER__DATABASE__WORLD__DATABASE=world"
      - "AVALON_SERVER__DATABASE__WORLD__USERNAME=root"
      - "AVALON_SERVER__DATABASE__WORLD__PASSWORD=123"
    ports:
      - "21000:21000"
