DROP TABLE IF EXISTS ItemTemplate;

CREATE TABLE IF NOT EXISTS ItemTemplate
(

    Id INT UNSIGNED PRIMARY KEY NOT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DELETE FROM ItemTemplate WHERE Id >= 0;
