<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\sgKey.snk</AssemblyOriginatorKeyFile>
    <PublicSign>true</PublicSign>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\sgKey.snk">
      <Link>sgKey.snk</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avalon.Balance.Core\Avalon.Balance.Core.csproj"/>
    <ProjectReference Include="..\Avalon.Database.World\Avalon.Database.World.csproj"/>
  </ItemGroup>

</Project>
