apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "avalon-api.fullname" . }}
  labels:
    {{- include "avalon-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "avalon-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "avalon-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "registry.nunolevezinho.xyz/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Database configuration
            - name: Database__Auth__ConnectionString
              value: {{ .Values.database.auth.connectionString | quote }}
            - name: Database__Characters__ConnectionString
              value: {{ .Values.database.characters.connectionString | quote }}
            - name: Database__World__ConnectionString
              value: {{ .Values.database.world.connectionString | quote }}
            - name: Application__Cache__Host
              value: {{ .Values.cache.host | quote }}
            - name: Application__Cache__Password
              value: {{ .Values.cache.password | quote }}
            - name: Application__Notification__Subject
              value: {{ .Values.notification.subject | quote }}
            - name: Application__Notification__PublicKey
              value: {{ .Values.notification.publicKey | quote }}
            - name: Application__Notification__PrivateKey
              value: {{ .Values.notification.privateKey | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
