server:
  infra:
    minUpdateDiff: 1
    maxCoreStuckTime: 60000
  network:
    tcp:
      enabled: true
      backlog: 128
    udp:
      enabled: false
      backlog: 128
  metrics:
    enabled: false
    apiUrl: localhost
    apiKey: apiKey
    automatic: false
    export: false
  database:
    auth:
      host:
      port:
      database:
      username:
      password:
    characters:
      host:
      port:
      database:
      username:
      password:
    world:
      host:
      port:
      database:
      username:
      password:
  game:
    playerRadius: 200

migrator:
  enabled:
  dryRun:
  createDatabases:
  applyMigrations:
  image:
    name: database-migrator
    repository: avalon/database-migrator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

replicaCount: 1

image:
  repository: avalon/world-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  #runAsUser: 0
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 21000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
