using System.Text.Json;
using System.Text.Json.Serialization;
using Avalon.Configuration;
using Avalon.Database.World;
using Avalon.Domain.World;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace Avalon.Exporter;

/// <summary>
/// Exports every quest's outline (#714): its title, its stages in order, each stage's objectives and what the quest
/// pays. The quest packets are self-describing, so the game client shows its own quest log without this file; it is
/// for offline tooling (a quest browser, documentation). Like ability-catalog, it reads the World database through
/// the same connection string, so it is reviewed as a data diff rather than held by a drift test.
/// </summary>
/// <remarks>
/// A hand-listed row, as in ability-catalog: the quest's script, level band and drops are server-only. Titles are
/// the base-locale (enUS) wording. Objective types are written as their numbers, the wire's QuestObjectiveKind,
/// listed in the $comment.
/// </remarks>
public static class QuestCatalogExport
{
    public const string DirectoryName = "quests";
    public const string FileName = "quest-catalog-v1.json";

    // camelCase, matching item-catalog-v1.json and ability-catalog-v1.json.
    private static readonly JsonSerializerOptions s_serializerOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>The same World connection string item-catalog reads, from the same sources (#557).</summary>
    public static string? Readiness() => ItemCatalog.Readiness();

    public static void Write(string path)
    {
        string connectionString = ItemCatalog.ConnectionString()
            ?? throw new InvalidOperationException("No World connection string; readiness should have caught this.");

        IOptions<DatabaseConfiguration> options = Options.Create(new DatabaseConfiguration
        {
            World = new DatabaseConnection { ConnectionString = connectionString }
        });

        using var context = new WorldDbContext(NullLoggerFactory.Instance, options);

        var quests = context.QuestTemplates
            .AsNoTracking()
            .AsSplitQuery()
            .Include(q => q.Stages)
            .Include(q => q.Objectives)
            .Include(q => q.ItemRewards)
            .ToList();
        var texts = context.LocalizedTexts.AsNoTracking()
            .ToDictionary(t => t.Id.Value, t => t.Text);

        Lf.Write(path, Render(quests, texts));
        Console.WriteLine($"wrote {path} ({quests.Count} quests)");
    }

    /// <summary>Pure, so the shape of the file is testable without a database.</summary>
    /// <param name="texts">Base-locale wording by text id; a title with no row is written as an empty string.</param>
    public static string Render(IReadOnlyCollection<QuestTemplate> quests, IReadOnlyDictionary<int, string> texts)
    {
        var document = new CatalogDocument(
            Comment: "Generated by tools/Avalon.Exporter -- quest-catalog. Do not edit by hand. " +
                     "title is the base-locale (enUS) wording. Stages run in order from sequence 0; every objective " +
                     "of a stage completes it. type: 1 kill, 2 collect, 3 talk, 4 scripted. targetId is a creature " +
                     "template for kill and talk, an item template for collect, 0 for scripted. money is copper.",
            Quests: quests.OrderBy(q => q.Id.Value).Select(q => Quest.From(q, texts)).ToList());

        return JsonSerializer.Serialize(document, s_serializerOptions) + "\n";
    }

    private sealed record CatalogDocument(
        [property: JsonPropertyName("$comment")] string Comment,
        List<Quest> Quests);

    private sealed record Quest(uint Id, string Title, List<Stage> Stages, Rewards Rewards)
    {
        public static Quest From(QuestTemplate q, IReadOnlyDictionary<int, string> texts) => new(
            q.Id.Value,
            texts.TryGetValue(q.TitleTextId.Value, out string? title) ? title : string.Empty,
            q.Stages.OrderBy(s => s.Sequence)
                .Select(s => new Stage(s.Sequence, q.Objectives
                    .Where(o => o.StageSequence == s.Sequence)
                    .OrderBy(o => o.Id)
                    .Select(Objective.From)
                    .ToList()))
                .ToList(),
            new Rewards(
                q.RewardExperience,
                q.RewardMoney,
                q.ItemRewards.OrderBy(r => r.ItemTemplateId.Value)
                    .Select(r => new RewardItem(r.ItemTemplateId.Value, r.Count))
                    .ToList()));
    }

    private sealed record Stage(int Sequence, List<Objective> Objectives);

    private sealed record Objective(uint Id, byte Type, ulong TargetId, uint Count)
    {
        public static Objective From(QuestObjective o) => new(
            o.Id, (byte)o.Type, o.CreatureTemplateId?.Value ?? o.ItemTemplateId?.Value ?? 0, o.Count);
    }

    private sealed record Rewards(uint Experience, ulong Money, List<RewardItem> Items);

    private sealed record RewardItem(ulong ItemTemplateId, uint Count);
}
