CREATE TABLE IF NOT EXISTS `__MigrationLock` (
  `Id` CHAR(36) NOT NULL,
  `Locked` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `LockedBy` VARCHAR(60) NOT NULL,
  `LockedAt` DATETIME NOT NULL,
  PRIMARY KEY (`Id`)
);
