using System.Globalization;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using Avalon.Network.Packets;
using Avalon.Network.Packets.Abstractions;

namespace Avalon.SchemaGen;

/// <summary>
/// Exports what a <c>.proto</c> file cannot carry: the opcode-to-message mapping and the
/// per-packet encryption flags.
/// </summary>
/// <remarks>
/// Opcode identity is not stored as data anywhere: the server derives it at startup by
/// reflecting a public static <see cref="NetworkPacketType"/> field off each packet class,
/// and a C++ client cannot reflect. The same is true of the flags that say whether a
/// packet is encrypted. This performs that reflection once, at export time, so both are
/// readable without a .NET runtime.
///
/// It once carried the entity-field bitmask as well, because entity state travelled as an
/// opaque bytes member that bitmask headed. Entity state is a message now and a client reads
/// which members arrived, so the bitmask is bookkeeping on this side that a client has no use
/// for and would be wrong to implement.
/// </remarks>
public static class OpcodeTable
{
    public const string FileName = "opcodes.json";

    public static string Generate()
    {
        List<OpcodeEntry> entries = [];
        Dictionary<NetworkPacketType, string> seen = [];

        const BindingFlags staticFields = BindingFlags.Public | BindingFlags.Static;

        foreach (Type type in WireSchema.ContractTypes())
        {
            if (!typeof(Packet).IsAssignableFrom(type))
            {
                continue;
            }

            FieldInfo[] fields = type.GetFields(staticFields);

            FieldInfo? opcodeField = Array.Find(fields, field => field.FieldType == typeof(NetworkPacketType));
            if (opcodeField is null)
            {
                continue;
            }

            var opcode = (NetworkPacketType)opcodeField.GetValue(null)!;

            if (seen.TryGetValue(opcode, out string? owner))
            {
                throw new InvalidOperationException(
                    $"Opcode {opcode} is claimed by both {owner} and {type.Name}. Dispatch by opcode is ambiguous, " +
                    "so the table would describe a protocol that cannot be decoded.");
            }

            seen.Add(opcode, type.Name);

            FieldInfo? flagsField = Array.Find(fields, field => field.FieldType == typeof(NetworkPacketFlags));
            var flags = (NetworkPacketFlags?)flagsField?.GetValue(null);

            entries.Add(new OpcodeEntry(
                Name: opcode.ToString(),
                Opcode: (short)opcode,
                Hex: "0x" + ((short)opcode).ToString("X4", CultureInfo.InvariantCulture),
                Message: WireSchema.SchemaNameOf(type),
                Direction: DirectionOf(opcode),
                Flags: flags is null ? null : (short)flags.Value,
                FlagNames: flags?.ToString()));
        }

        entries.Sort((left, right) => left.Opcode.CompareTo(right.Opcode));

        var table = new OpcodeTableDocument(
            Comment: "Generated by tools/Avalon.SchemaGen alongside " + WireSchema.FileName + ". Do not edit by hand.",
            Packets: entries);

        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            DefaultIgnoreCondition = JsonIgnoreCondition.Never,
        };

        return JsonSerializer.Serialize(table, options).Replace("\r\n", "\n", StringComparison.Ordinal) + "\n";
    }

    /// <summary>
    /// The opcode name prefix is the only statement of direction the codebase makes.
    /// </summary>
    private static string DirectionOf(NetworkPacketType opcode)
    {
        string name = opcode.ToString();

        if (name.StartsWith("CMSG_", StringComparison.Ordinal))
        {
            return "ClientToServer";
        }

        if (name.StartsWith("SMSG_", StringComparison.Ordinal))
        {
            return "ServerToClient";
        }

        return "Unknown";
    }

    private sealed record OpcodeTableDocument(
        [property: JsonPropertyName("$comment")] string Comment,
        [property: JsonPropertyName("packets")] IReadOnlyList<OpcodeEntry> Packets);

    private sealed record OpcodeEntry(
        [property: JsonPropertyName("name")] string Name,
        [property: JsonPropertyName("opcode")] short Opcode,
        [property: JsonPropertyName("hex")] string Hex,
        [property: JsonPropertyName("message")] string Message,
        [property: JsonPropertyName("direction")] string Direction,
        [property: JsonPropertyName("flags")] short? Flags,
        [property: JsonPropertyName("flagNames")] string? FlagNames);
}
