using Avalon.ChunkGen;
using Xunit;

namespace Avalon.Server.World.UnitTests.Procedural;

/// <summary>
/// The tool's command line against a copy of the committed Maps/. No case here bakes a piece: the bake changes the
/// process working directory, which other tests read.
/// </summary>
public sealed class ChunkGenCliShould : IDisposable
{
    private readonly string _maps = Path.Combine(Path.GetTempPath(), $"avalon-chunkgen-cli-{Guid.NewGuid():N}");
    private readonly StringWriter _output = new();
    private readonly StringWriter _error = new();

    public ChunkGenCliShould() => ChunkGenWritersShould.CopyDirectory(Path.Combine(AppContext.BaseDirectory, "Maps"), _maps);

    public void Dispose()
    {
        if (Directory.Exists(_maps)) Directory.Delete(_maps, recursive: true);
    }

    [Fact]
    public async Task Exit_1_and_write_nothing_on_an_authoring_error()
    {
        Dictionary<string, string> before = Snapshot();
        var crossing = new ChunkGroupPiece("forest_bad_group", [(0, 0, Side.S)], [new BoxBlocker(25, 35, 5, 10)], [], ["forest"]);
        var fine = new ChunkPiece("forest_fine", [Side.N], [], [], ["forest"]);

        int code = await ChunkGenCli.RunAsync(["forest", "--maps", _maps], () => [fine], () => [crossing], _output, _error);

        Assert.Equal(1, code);
        Assert.StartsWith("nothing written: InvalidOperationException: forest_bad_group", _error.ToString(), StringComparison.Ordinal);
        Assert.Equal(before, Snapshot());
    }

    [Theory]
    [InlineData]
    [InlineData("town")]
    [InlineData("forest", "--maps")]
    [InlineData("forest", "--map", "x")]
    [InlineData("forest", "--maps", "x", "extra")]
    [InlineData("forest", "extra")]
    public async Task Refuse_arguments_it_does_not_know(params string[] args)
    {
        int code = await ChunkGenCli.RunAsync(args, () => [], () => [], _output, _error);

        Assert.Equal(1, code);
        Assert.Equal(ChunkGenCli.Usage, _error.ToString().Trim());
    }

    [Fact]
    public async Task List_forest_chunks_it_did_not_generate_without_deleting_them()
    {
        Dictionary<string, string> before = Snapshot();

        int code = await ChunkGenCli.RunAsync(["forest", "--maps", _maps], () => [], () => [], _output, _error);

        Assert.Equal(0, code);
        string output = _output.ToString();
        Assert.Contains("not generated by ChunkGen: forest_boss_01.obj", output, StringComparison.Ordinal);
        Assert.Contains("not generated by ChunkGen: forest_boss_01.json", output, StringComparison.Ordinal);
        Assert.DoesNotContain("town", output.Replace(_maps, "", StringComparison.Ordinal), StringComparison.Ordinal);
        Assert.Equal(before, Snapshot());
    }

    /// <summary>
    /// A temporary copy that cannot be removed is reported, never thrown over the exit code. The delete is made to fail
    /// directly: a file held open blocks it on Windows only, so it would prove nothing on Linux.
    /// </summary>
    [Fact]
    public void Report_a_staging_copy_it_cannot_remove_without_throwing()
    {
        string staging = Path.Combine(Path.GetTempPath(), $"avalon-chunkgen-staging-{Guid.NewGuid():N}");
        Directory.CreateDirectory(staging);
        try
        {
            ChunkGenCli.DeleteStaging(staging, _error, _ => throw new IOException("in use"));

            Assert.StartsWith($"could not remove the temporary copy {staging}: ", _error.ToString(), StringComparison.Ordinal);
        }
        finally
        {
            if (Directory.Exists(staging)) Directory.Delete(staging, recursive: true);
        }
    }

    [Fact]
    public void Remove_a_staging_copy_and_say_nothing()
    {
        string staging = Path.Combine(Path.GetTempPath(), $"avalon-chunkgen-staging-{Guid.NewGuid():N}");
        Directory.CreateDirectory(Path.Combine(staging, "Maps"));

        ChunkGenCli.DeleteStaging(staging, _error);

        Assert.False(Directory.Exists(staging));
        Assert.Empty(_error.ToString());
    }

    private Dictionary<string, string> Snapshot() =>
        Directory.EnumerateFiles(_maps, "*", SearchOption.AllDirectories)
            .ToDictionary(f => Path.GetRelativePath(_maps, f), File.ReadAllText, StringComparer.Ordinal);
}
