apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "avalon-server.fullname" . }}
  labels:
    {{- include "avalon-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "avalon-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "avalon-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "registry.nunolevezinho.xyz/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            # Hosting configuration
            - name: Hosting__Host
              value: {{ .Values.server.hosting.host | quote }}
            - name: Hosting__Port
              value: {{ .Values.service.port }}
            # Cache configuration
            - name: Cache__Host
              value: {{ .Values.server.cache.host | quote }}
            - name: Cache__Password
              value: {{ .Values.server.cache.password | quote }}
            # Database configuration
            - name: Database__Auth__ConnectionString
              value: {{ .Values.server.database.auth.connectionString | quote }}
            - name: Database__Characters__ConnectionString
              value: {{ .Values.server.database.characters.connectionString | quote }}
            - name: Database__World__ConnectionString
              value: {{ .Values.server.database.world.connectionString | quote }}
            # Game configuration
            - name: Game__WorldId
              value: {{ .Values.server.game.worldId }}
            - name: Game__PlayerRadius
              value: {{ .Values.server.game.playerRadius }}
            - name: Game__MaxPlayersPerAccount
              value: {{ .Values.server.game.maxPlayersPerAccount }}
          ports:
            - name: server-tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: server-tcp
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: server-tcp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
