using System.Text.Json;
using System.Text.Json.Serialization;
using Avalon.Configuration;
using Avalon.Database;
using Avalon.Database.World;
using Avalon.Domain.World;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace Avalon.Exporter;

/// <summary>
/// Exports the ability rows the client needs to name and draw every ability it is sent (#163): the player
/// kit's and the creatures' alike, since the client learns ability data for its own character only
/// (SMSG_CHARACTER_ABILITIES), and SMSG_UNIT_START_CAST, SMSG_ABILITY_FIRED and the damage packets carry
/// nothing but an ability id. Each row is the shape and timing a client draws a cast, a wind-up telegraph or a
/// fired shape from. Like item-catalog, it reads the World database, the same source through the same
/// connection string, so it is reviewed as a data diff rather than held by a drift test.
/// </summary>
/// <remarks>
/// A hand-listed row, unlike item-catalog's whole entity: an ability row carries server-only balance
/// (coefficients, threat, costs, the script name) that the client has no use for and should not come to
/// depend on. Enumerations are written as their numbers, listed in the $comment.
/// </remarks>
public static class AbilityCatalogExport
{
    public const string DirectoryName = "abilities";
    public const string FileName = "ability-catalog-v1.json";

    // camelCase, matching item-catalog-v1.json.
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>The same World connection string item-catalog reads, from the same sources (#557).</summary>
    public static string? Readiness() => ItemCatalog.Readiness();

    public static void Write(string path)
    {
        string connectionString = ItemCatalog.ConnectionString()
            ?? throw new InvalidOperationException("No World connection string; readiness should have caught this.");

        IOptions<DatabaseConfiguration> options = Options.Create(new DatabaseConfiguration
        {
            World = new DatabaseConnection { ConnectionString = connectionString }
        });

        using var context = new WorldDbContext(NullLoggerFactory.Instance, options);

        List<AbilityTemplate> templates = context.AbilityTemplates.AsNoTracking().ToList();

        Lf.Write(path, Render(templates));
        Console.WriteLine($"wrote {path} ({templates.Count} ability templates)");
    }

    /// <summary>Pure, so the shape of the file is testable without a database.</summary>
    public static string Render(IReadOnlyCollection<AbilityTemplate> templates)
    {
        var document = new CatalogDocument(
            Comment: "Generated by tools/Avalon.Exporter -- ability-catalog. Do not edit by hand. " +
                     "shape: 0 circle, 1 cone, 2 projectile. aimMode: 0 movement (along the facing of the caster), " +
                     "1 cursor (at a ground point). anchor, where a circle is centred: 0 caster, 1 aim point. " +
                     "affects: 0 hostile (damaged), 1 ally (healed). Distances in metres, arcDegrees the full arc " +
                     "of a cone, projectileSpeed in metres per second, castTimeMs and cooldownMs in milliseconds " +
                     "before haste. The basic of a creature waits its swing interval rather than its cooldownMs. " +
                     "auraId: the aura each unit the ability affects receives (see aura-catalog), or null.",
            Abilities: templates.OrderBy(template => template.Id.Value).Select(Row.From).ToList());

        return JsonSerializer.Serialize(document, SerializerOptions) + "\n";
    }

    private sealed record CatalogDocument(
        [property: JsonPropertyName("$comment")] string Comment,
        List<Row> Abilities);

    /// <summary>What a client needs to name and draw an ability.</summary>
    private sealed record Row(
        uint Id,
        string Name,
        byte Shape,
        byte AimMode,
        byte Anchor,
        byte Affects,
        float Radius,
        float Reach,
        float ArcDegrees,
        float ProjectileSpeed,
        bool Pierce,
        uint CastTimeMs,
        uint CooldownMs,
        uint? AuraId)
    {
        public static Row From(AbilityTemplate t) => new(
            t.Id.Value, t.Name ?? string.Empty, (byte)t.Shape, (byte)t.AimMode, (byte)t.Anchor, (byte)t.Affects,
            t.Radius, t.Reach, t.ArcDegrees, t.ProjectileSpeed, t.Pierce, t.CastTime, t.Cooldown, t.AuraId?.Value);
    }
}
