name: .NET PR Pipeline

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # Pull Repos
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
      - name: Publish World Server
        run: dotnet publish src/Server/Avalon.Server.World/Avalon.Server.World.csproj -c Release --no-restore
      - name: Publish Auth Server
        run: dotnet publish src/Server/Avalon.Server.Auth/Avalon.Server.Auth.csproj -c Release --no-restore
      - name: Publish Api
        run: dotnet publish src/Server/Avalon.Api/Avalon.Api.csproj -c Release --no-restore
