CREATE DATABASE `world` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;

CREATE DATABASE `characters` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;

CREATE DATABASE `auth` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;
